import type { Product } from "./products";
import { img } from "./images";
import { shopNowProducts, shopNowTree } from "./shop-now-data";

export const shopCategories = [
  { slug: "brass-binocular", name: "Handheld Brass Binoculars" },
  { slug: "brass-spyglass-telescope", name: "Brass Spyglasses" },
  { slug: "brass-telescope-tripod", name: "Floor Telescopes on Tripod" },
  { slug: "brass-telescope-stand", name: "Tabletop Telescope Stands" },
  { slug: "brass-binocular-tripod", name: "Observation Binoculars on Tripod" },
  { slug: "brass-lamp-tripod", name: "Marine Tripod Lamps" },
  { slug: "wooden-ship-wheel", name: "Wooden Ship Wheels" },
  { slug: "royal-lamp-tripod", name: "Royal Floor Lamps" },
  { slug: "armor-breast-plate", name: "Armor Breast Plate & Jackets" },
  { slug: "armor-helmets", name: "Armor Helmets" },
  { slug: "muscle-armour", name: "Muscle Armour" },
  { slug: "full-suit-of-armor", name: "Full Suit of Armor" },
  { slug: "armory-props", name: "Armory Props" },
  { slug: "diving-helmets", name: "Diving Helmets" },
  { slug: "brass-nautical-telescope", name: "Brass Spyglasses" },
  { slug: "brass-nautical-binocular", name: "Handheld Brass Binoculars" },
  { slug: "compass", name: "Compass" },
  { slug: "spotlight-searchlight", name: "Spotlight / Searchlight" },
  { slug: "keyring-keychain", name: "Keyring / Keychain / Pen" },
  { slug: "sand-timer", name: "Sand Timer" },
  { slug: "clocks", name: "Clocks" },
  { slug: "nautical-brass-sextant", name: "Nautical Brass Sextant" },
  { slug: "magnifying-glass", name: "Magnifying Glass" },
  { slug: "ship-wheels", name: "Ship Wheels" },
  { slug: "ship-bell", name: "Ship Bell" },
  { slug: "ship-telegraph", name: "Ship Telegraph" },
  { slug: "walking-stick", name: "Walking Stick & Shoe Horn" },
  { slug: "nautical-decor-gifts", name: "Nautical Decor & Gifts" },
  { slug: "ungrouped", name: "Ungrouped" },
];

export const shopNowCategories = shopNowTree.map((c) => ({ slug: c.slug, name: c.name }));

const collectionMap: Record<string, string> = {
  "brass-compasses": "compass",
  telescopes: "brass-spyglass-telescope",
  "brass-binoculars": "brass-binocular",
  "nautical-instruments": "nautical-brass-sextant",
  "nautical-decor": "nautical-decor-gifts",
  "walking-canes": "walking-stick",
  "ship-wheels": "wooden-ship-wheel",
  "corporate-gifts": "nautical-decor-gifts",
  "custom-manufacturing": "ungrouped",
  "new-arrivals": "ungrouped",
};

const slugMap: Record<string, string> = {
  "diving-helmet-decor": "diving-helmets",
  "brass-sextant": "nautical-brass-sextant",
  "brass-hourglass": "sand-timer",
  "map-magnifier-brass": "magnifying-glass",
  "ship-bell-brass": "ship-bell",
  "ship-lantern-brass": "spotlight-searchlight",
};

export function getProductCategory(p: Product) {
  return p.category || slugMap[p.slug] || collectionMap[p.collection] || "ungrouped";
}

function compactUsd(n: number) {
  if (Number.isInteger(n)) return `$${n}`;
  return `$${n.toFixed(2).replace(/\.00$/, "")}`;
}

export function formatOfferPrice(p: Product) {
  const min = p.wholesaleFrom ?? p.price;
  const max = p.price;
  if (min >= max) return `${compactUsd(max)} USD`;
  return `${compactUsd(min)}-${compactUsd(max).replace("$", "")}`;
}

function item(
  data: Pick<Product, "slug" | "name" | "sku" | "price" | "collection" | "image"> &
    Partial<Product>
): Product {
  const image = data.image;
  return {
    rating: 4.6,
    reviews: 32,
    stock: "in-stock",
    finish: "Antique / polished",
    material: data.material || "Brass / steel / wood",
    dimensions: data.dimensions || "As pictured",
    weight: data.weight || "—",
    packaging: "Export carton",
    included: ["Product", "Export packing"],
    description: data.description || data.name,
    story: "Handcrafted for wholesale export from India. Logo and packaging programmes available.",
    moq: 24,
    ...data,
    image,
    gallery: data.gallery || [image],
  };
}

export const catalogProducts: Product[] = [
  item({
    slug: "shiny-brass-marine-mini-telescope",
    name: 'Polished Draw-Tube Mini Telescope 6"',
    sku: "MM-TEL-006",
    price: 4.95,
    wholesaleFrom: 3,
    moq: 120,
    collection: "telescopes",
    category: "brass-spyglass-telescope",
    image: img.telescope,
    featured: true,
  }),
  item({
    slug: "medieval-knight-templar-armor",
    name: "Medieval Knight Templar Antique Imitation 18 Gauge Solid Steel Armor",
    sku: "MM-ARM-018",
    price: 695,
    wholesaleFrom: 595,
    moq: 2,
    collection: "nautical-decor",
    category: "full-suit-of-armor",
    material: "18 gauge solid steel",
    image: img.armor,
  }),
  item({
    slug: "brass-wood-ship-engine-telegraph",
    name: '18" Handmade Antique Brass & Wood Ship Engine Order Telegraph',
    sku: "MM-TELG-018",
    price: 20.99,
    wholesaleFrom: 19.99,
    moq: 60,
    collection: "nautical-instruments",
    category: "ship-telegraph",
    image: img.antiques4,
  }),
  item({
    slug: "leather-cover-boxed-telescope",
    name: "Leather-Cased Brass Telescope in Wooden Box",
    sku: "MM-TEL-012",
    price: 4.95,
    wholesaleFrom: 3.99,
    moq: 120,
    collection: "telescopes",
    category: "brass-spyglass-telescope",
    image: img.telescopeAstro,
  }),
  item({
    slug: "antique-designer-diving-helmet",
    name: "Decorative Antique Nautical Designer Lightweight Handmade Diving Helmet",
    sku: "MM-DIV-040",
    price: 45,
    wholesaleFrom: 40,
    moq: 10,
    collection: "nautical-decor",
    category: "diving-helmets",
    image: img.diving,
  }),
  item({
    slug: "templar-warrior-armor-shield",
    name: "Custom Printed Polished Medieval Warrior Armor Templar Shield",
    sku: "MM-ARM-033",
    price: 35,
    wholesaleFrom: 30,
    moq: 12,
    collection: "nautical-decor",
    category: "armory-props",
    image: img.knight,
  }),
  item({
    slug: "wooden-cross-necklace",
    name: "Wooden Cross Necklace for Men Christian Brown/Black Stainless Chain",
    sku: "MM-GFT-040",
    price: 2.2,
    wholesaleFrom: 1.2,
    moq: 200,
    collection: "corporate-gifts",
    category: "ungrouped",
    image: img.jewelry,
  }),
  item({
    slug: "wooden-ship-wheel-12-diy",
    name: 'European Style Ship Wheel 12"',
    sku: "MM-WHL-012",
    price: 8.99,
    wholesaleFrom: 6.25,
    moq: 24,
    collection: "ship-wheels",
    category: "wooden-ship-wheel",
    image: img.sailboat,
  }),
  item({
    slug: "steel-breast-plate-jacket",
    name: "Medieval Steel Breast Plate & Jacket Antique Finish Wearable Armor",
    sku: "MM-ARM-002",
    price: 189,
    wholesaleFrom: 149,
    moq: 4,
    collection: "nautical-decor",
    category: "armor-breast-plate",
    image: img.armor,
  }),
  item({
    slug: "roman-armor-helmet",
    name: "Roman Centurion Brass & Steel Armor Helmet with Plume",
    sku: "MM-ARM-009",
    price: 79,
    wholesaleFrom: 62,
    moq: 8,
    collection: "nautical-decor",
    category: "armor-helmets",
    image: img.helmet,
  }),
  item({
    slug: "greek-muscle-armour-cuirass",
    name: "Greek Muscle Armour Cuirass Antique Brass Finish Display Piece",
    sku: "MM-ARM-011",
    price: 259,
    wholesaleFrom: 210,
    moq: 2,
    collection: "nautical-decor",
    category: "muscle-armour",
    image: img.armor,
  }),
  item({
    slug: "marine-searchlight-brass",
    name: "Antique Brass Marine Spotlight / Searchlight with Wooden Base",
    sku: "MM-LGT-008",
    price: 42,
    wholesaleFrom: 28,
    moq: 20,
    collection: "nautical-decor",
    category: "spotlight-searchlight",
    image: img.lanternCandle,
  }),
  item({
    slug: "brass-compass-keyring",
    name: "Brass Compass Keyring / Keychain / Pen Gift Set Wholesale",
    sku: "MM-KEY-003",
    price: 2.5,
    wholesaleFrom: 0.95,
    moq: 300,
    collection: "corporate-gifts",
    category: "keyring-keychain",
    image: img.compassGold,
  }),
  item({
    slug: "brass-sand-timer-30min",
    name: "Nautical Brass Sand Timer 30 Minute Hourglass Desk Piece",
    sku: "MM-SND-030",
    price: 12,
    wholesaleFrom: 7.5,
    moq: 48,
    collection: "nautical-instruments",
    category: "sand-timer",
    image: img.hourglassSand,
  }),
  item({
    slug: "maritime-brass-desk-clock",
    name: "Maritime Brass Desk Clock with Compass Dial",
    sku: "MM-CLK-004",
    price: 18,
    wholesaleFrom: 11,
    moq: 40,
    collection: "nautical-instruments",
    category: "clocks",
    image: img.clock,
  }),
  item({
    slug: "navigational-brass-sextant-box",
    name: "Nautical Brass Sextant with Wooden Instrument Box",
    sku: "MM-SXT-007",
    price: 39,
    wholesaleFrom: 24,
    moq: 16,
    collection: "nautical-instruments",
    category: "nautical-brass-sextant",
    image: img.compassMap,
  }),
  item({
    slug: "brass-magnifying-glass-handle",
    name: "Antique Brass Magnifying Glass with Turned Handle",
    sku: "MM-MAG-005",
    price: 8.5,
    wholesaleFrom: 4.2,
    moq: 80,
    collection: "nautical-instruments",
    category: "magnifying-glass",
    image: img.magnifier,
  }),
  item({
    slug: "polished-brass-ship-bell",
    name: "Polished Brass Ship Bell with Wall Bracket and Lanyard",
    sku: "MM-BEL-006",
    price: 22,
    wholesaleFrom: 14,
    moq: 20,
    collection: "nautical-decor",
    category: "ship-bell",
    image: img.antiques,
  }),
  item({
    slug: "brass-shoe-horn-walking-set",
    name: "Brass Shoe Horn & Walking Stick Handle Gift Set",
    sku: "MM-CAN-014",
    price: 16,
    wholesaleFrom: 9.5,
    moq: 36,
    collection: "walking-canes",
    category: "walking-stick",
    image: img.antiques3,
  }),
  item({
    slug: "brass-nautical-binocular-officer",
    name: "Navy Officer Binocular with Leather Wrap",
    sku: "MM-BIN-020",
    price: 29,
    wholesaleFrom: 18,
    moq: 24,
    collection: "brass-binoculars",
    category: "brass-binocular",
    image: img.binocularsMap,
  }),
  item({
    slug: "pocket-brass-compass-wholesale",
    name: "Antique Pocket Brass Compass Wholesale Gift / Décor",
    sku: "MM-CMP-050",
    price: 6.5,
    wholesaleFrom: 3.2,
    moq: 100,
    collection: "brass-compasses",
    category: "compass",
    image: img.compassBrass,
  }),
  item({
    slug: "steel-breast-plate-polished",
    name: "Polished Steel Breast Plate Wearable Armor Jacket",
    sku: "MM-ARM-003",
    price: 175,
    wholesaleFrom: 139,
    moq: 4,
    collection: "nautical-decor",
    category: "armor-breast-plate",
    image: img.armor,
  }),
  item({
    slug: "antique-breast-plate-brass-trim",
    name: "Antique Finish Breast Plate with Brass Trim",
    sku: "MM-ARM-004",
    price: 199,
    wholesaleFrom: 155,
    moq: 4,
    collection: "nautical-decor",
    category: "armor-breast-plate",
    image: img.knight,
  }),
  item({
    slug: "display-breast-plate-stand",
    name: "Display Steel Breast Plate with Wooden Stand",
    sku: "MM-ARM-005",
    price: 165,
    wholesaleFrom: 128,
    moq: 4,
    collection: "nautical-decor",
    category: "armor-breast-plate",
    image: img.armor,
  }),
  item({
    slug: "spartan-armor-helmet-brass",
    name: "Spartan Brass & Steel Armor Helmet",
    sku: "MM-ARM-010",
    price: 85,
    wholesaleFrom: 68,
    moq: 8,
    collection: "nautical-decor",
    category: "armor-helmets",
    image: img.helmet,
  }),
  item({
    slug: "medieval-knight-helmet-visor",
    name: "Medieval Knight Helmet with Moving Visor",
    sku: "MM-ARM-012",
    price: 92,
    wholesaleFrom: 74,
    moq: 6,
    collection: "nautical-decor",
    category: "armor-helmets",
    image: img.knight,
  }),
  item({
    slug: "roman-galea-helmet-display",
    name: "Roman Galea Armor Helmet Display Piece",
    sku: "MM-ARM-013",
    price: 69,
    wholesaleFrom: 54,
    moq: 8,
    collection: "nautical-decor",
    category: "armor-helmets",
    image: img.helmet,
  }),
  item({
    slug: "greek-muscle-armour-polished",
    name: "Polished Greek Muscle Armour Cuirass",
    sku: "MM-ARM-015",
    price: 249,
    wholesaleFrom: 198,
    moq: 2,
    collection: "nautical-decor",
    category: "muscle-armour",
    image: img.armor,
  }),
  item({
    slug: "roman-muscle-armour-antique",
    name: "Roman Muscle Armour Antique Brass Finish",
    sku: "MM-ARM-016",
    price: 239,
    wholesaleFrom: 190,
    moq: 2,
    collection: "nautical-decor",
    category: "muscle-armour",
    image: img.knight,
  }),
  item({
    slug: "display-muscle-cuirass-stand",
    name: "Display Muscle Cuirass with Stand",
    sku: "MM-ARM-017",
    price: 219,
    wholesaleFrom: 175,
    moq: 2,
    collection: "nautical-decor",
    category: "muscle-armour",
    image: img.armor,
  }),
  item({
    slug: "full-suit-armor-blackened",
    name: "Full Suit of Armor Blackened Steel Display",
    sku: "MM-ARM-019",
    price: 720,
    wholesaleFrom: 610,
    moq: 2,
    collection: "nautical-decor",
    category: "full-suit-of-armor",
    image: img.knight,
  }),
  item({
    slug: "full-suit-armor-polished",
    name: "Full Suit of Armor Polished Steel with Sword",
    sku: "MM-ARM-020",
    price: 745,
    wholesaleFrom: 625,
    moq: 2,
    collection: "nautical-decor",
    category: "full-suit-of-armor",
    image: img.armor,
  }),
  item({
    slug: "full-suit-armor-wearable",
    name: "Wearable Full Suit of Armor 18 Gauge",
    sku: "MM-ARM-021",
    price: 780,
    wholesaleFrom: 650,
    moq: 1,
    collection: "nautical-decor",
    category: "full-suit-of-armor",
    image: img.knight,
  }),
  item({
    slug: "templar-shield-antique",
    name: "Templar Shield Antique Finish Armory Prop",
    sku: "MM-ARM-034",
    price: 32,
    wholesaleFrom: 26,
    moq: 12,
    collection: "nautical-decor",
    category: "armory-props",
    image: img.knight,
  }),
  item({
    slug: "medieval-sword-display",
    name: "Medieval Sword Display Armory Prop",
    sku: "MM-ARM-035",
    price: 28,
    wholesaleFrom: 22,
    moq: 12,
    collection: "nautical-decor",
    category: "armory-props",
    image: img.armor,
  }),
  item({
    slug: "brass-armor-gauntlet",
    name: "Brass Armor Gauntlet Pair Armory Prop",
    sku: "MM-ARM-036",
    price: 39,
    wholesaleFrom: 31,
    moq: 10,
    collection: "nautical-decor",
    category: "armory-props",
    image: img.helmet,
  }),
  item({
    slug: "mark-v-diving-helmet",
    name: "Mark V Style Brass Diving Helmet",
    sku: "MM-DIV-041",
    price: 255,
    wholesaleFrom: 198,
    moq: 4,
    collection: "nautical-decor",
    category: "diving-helmets",
    image: img.diving,
  }),
  item({
    slug: "tabletop-diving-helmet",
    name: "Tabletop Decorative Diving Helmet Brass",
    sku: "MM-DIV-042",
    price: 38,
    wholesaleFrom: 29,
    moq: 12,
    collection: "nautical-decor",
    category: "diving-helmets",
    image: img.ocean,
  }),
  item({
    slug: "officer-binocular-canvas-case",
    name: "Field Officer Binocular with Canvas Case",
    sku: "MM-BIN-021",
    price: 32,
    wholesaleFrom: 21,
    moq: 20,
    collection: "brass-binoculars",
    category: "brass-binocular",
    image: img.binoculars,
  }),
  item({
    slug: "marine-searchlight-bulkhead",
    name: "Deckhouse Bulkhead Searchlight",
    sku: "MM-LGT-009",
    price: 48,
    wholesaleFrom: 34,
    moq: 16,
    collection: "nautical-decor",
    category: "spotlight-searchlight",
    image: img.lanternOil,
  }),
  item({
    slug: "ship-lantern-searchlight-pair",
    name: "Ship Lantern Searchlight Pair with Wooden Base",
    sku: "MM-LGT-010",
    price: 55,
    wholesaleFrom: 39,
    moq: 12,
    collection: "nautical-decor",
    category: "spotlight-searchlight",
    image: img.lanternVintage,
  }),
  ...shopNowProducts,
];
