import type { Product } from "./products";
import { img } from "./images";

export type ShopNowChild = { slug: string; name: string; children?: ShopNowChild[] };

const kitchenTypes = (material: string) => [
  { slug: `${material}-cookware`, name: "Cookware" },
  { slug: `${material}-cutleries`, name: "Cutleries" },
  { slug: `${material}-drinkware`, name: "Drinkware" },
  { slug: `${material}-servewares`, name: "Servewares" },
  { slug: `${material}-storage-wares`, name: "Storage wares" },
  { slug: `${material}-tea-strainer-infuser`, name: "Tea Strainer/Infuser" },
];
export type ShopNowParent = {
  slug: string;
  name: string;
  children: ShopNowChild[];
};

export const shopNowTree: ShopNowParent[] = [
  {
    slug: "brass-binocular",
    name: "Handheld Brass Binoculars",
    children: [
      { slug: "handheld-brass-binocular", name: "Antique Field Binocular 6×30" },
      { slug: "officer-field-binocular", name: "Officer Leather Binocular 8×40" },
      { slug: "brass-handheld-binocular", name: "Polished Pocket Binocular 4×30" },
    ],
  },
  {
    slug: "brass-spyglass-telescope",
    name: "Brass Spyglasses",
    children: [
      { slug: "leather-wrapped-spyglass", name: "Leather-Wrapped Handheld Spyglass" },
      { slug: "handheld-brass-spyglass", name: "Retractable Brass Pocket Spyglass" },
      { slug: "handheld-retractable-telescope", name: 'Marine Mini Spyglass 6"' },
    ],
  },
  {
    slug: "brass-telescope-tripod",
    name: "Floor Telescopes on Tripod",
    children: [
      { slug: "vintage-brass-telescope-wood-tripod", name: "Vintage Telescope on Wooden Tripod" },
      { slug: "nautical-spyglass-tripod", name: "Nautical Spyglass on Studio Tripod" },
      { slug: "marine-telescope-brass-tripod", name: "Marine Telescope on Brass Tripod" },
      { slug: "floor-telescope", name: "Adjustable Floor Standing Telescope" },
    ],
  },
  {
    slug: "brass-telescope-stand",
    name: "Tabletop Telescope Stands",
    children: [
      { slug: "tabletop-brass-telescope-stand", name: "Desk Telescope on Short Stand" },
      { slug: "tabletop-telescope-stand", name: "Tabletop Brass Telescope with Base" },
    ],
  },
  {
    slug: "brass-binocular-tripod",
    name: "Observation Binoculars on Tripod",
    children: [
      { slug: "binocular-telescope-wood-tripod", name: "Dual-Head Binocular on Wooden Tripod" },
      { slug: "brass-tripod-binocular", name: "Brass Observation Binocular on Tripod" },
    ],
  },
  {
    slug: "brass-lamp-tripod",
    name: "Marine Tripod Lamps",
    children: [
      { slug: "marine-brass-lamp-tripod", name: "Marine Oil Lamp on Wooden Tripod" },
    ],
  },
  {
    slug: "wooden-ship-wheel",
    name: "Wooden Ship Wheels",
    children: [
      { slug: "handmade-wooden-ship-wheel", name: 'Handmade Teak Ship Wheel 18"' },
    ],
  },
  {
    slug: "royal-lamp-tripod",
    name: "Royal Floor Lamps",
    children: [
      { slug: "royal-brass-lamp-tripod", name: "Royal Brass Floor Lamp on Tripod" },
    ],
  },
  {
    slug: "armor-breast-plate",
    name: "Armor Breast Plate & Jackets",
    children: [
      { slug: "gloves", name: "Steel Armor Combat Gloves" },
    ],
  },
  {
    slug: "armor-helmets",
    name: "Armor Helmets",
    children: [
      { slug: "roman-centurion-helmet", name: "Roman Centurion Helmet with Plume" },
      { slug: "armor-shield", name: "Heraldic Knight Shield" },
      { slug: "norman-knight-helmet", name: "Norman Knight Nasal Helmet" },
      { slug: "movie-replica-armor-helmet", name: "Movie Replica Armor Helmet" },
      { slug: "corinthian-armor-helmet", name: "Corinthian Greek Helmet" },
      { slug: "german-armor-helmet", name: "German Sallet Helmet" },
      { slug: "roman-armor-helmet", name: "Roman Legionary Helmet" },
      { slug: "medieval-armor-helmet", name: "Medieval Great Helm" },
    ],
  },
  {
    slug: "muscle-armour",
    name: "Muscle Armour",
    children: [
      { slug: "steel-shield", name: "Solid Steel Battle Shield" },
      { slug: "armour-shield", name: "Round Brass-Rimmed Shield" },
      { slug: "muscle-armor", name: "Greek Muscle Cuirass" },
      { slug: "leather-muscle-armor", name: "Leather Muscle Cuirass" },
    ],
  },
  {
    slug: "armory-props",
    name: "Armory Props",
    children: [
      { slug: "medieval-shield", name: "Medieval Heater Shield" },
      { slug: "chainmail-armor", name: "Chainmail Hauberk" },
      { slug: "roman-legion-belt", name: "Roman Legion Cingulum Belt" },
      { slug: "armor-shoes-sandals", name: "Roman Armor Caligae Sandals" },
      { slug: "armor-gauntlet", name: "Steel Armor Gauntlet" },
      { slug: "armor-hand-leg-guard", name: "Armor Vambrace & Greave Set" },
      { slug: "armor-shoulder", name: "Armor Pauldron Shoulder Guard" },
    ],
  },
  {
    slug: "compass",
    name: "Compass",
    children: [
      { slug: "push-button-compass", name: "Push-Button Pocket Compass" },
      { slug: "compass-with-lid", name: "Hinged-Lid Desk Compass" },
      { slug: "flat-compass", name: "Flat Card Compass" },
      { slug: "brunton-compass", name: "Brunton Survey Compass" },
      { slug: "sundial-compass", name: "Brass Sundial Compass" },
    ],
  },
  {
    slug: "spotlight-searchlight",
    name: "Spotlight / Searchlight",
    children: [
      { slug: "table-lamp", name: "Brass Cabin Table Lamp" },
      { slug: "spot-light", name: "Marine Deck Spot Light" },
      { slug: "spotlight", name: "Brass Bulkhead Searchlight" },
      { slug: "floor-lamp", name: "Nautical Floor Lantern" },
    ],
  },
  {
    slug: "clocks",
    name: "Clocks",
    children: [
      { slug: "pocket-watches", name: "Brass Open-Face Pocket Watch" },
      { slug: "table-clocks", name: "Maritime Desk Clock" },
      { slug: "brass-table-watch", name: "Brass Table Watch with Compass Dial" },
      { slug: "nautical-pocket-watch", name: "Nautical Pocket Watch on Chain" },
    ],
  },
  {
    slug: "ship-bell",
    name: "Ship Bell",
    children: [
      { slug: "hand-bell", name: "Brass Hand Bell" },
      { slug: "hanging-bell", name: "Hanging Ship Bell with Bracket" },
      { slug: "desk-bell", name: "Captain’s Desk Bell" },
    ],
  },
  {
    slug: "nautical-decor-gifts",
    name: "Nautical Decor & Gifts",
    children: [
      { slug: "brass-burner", name: "Brass Incense Burner" },
      { slug: "pen-holder", name: "Brass Desk Pen Holder" },
      { slug: "wooden-mug", name: "Turned Wooden Tankard" },
      { slug: "wooden-game", name: "Wooden Chess & Board Game" },
      { slug: "wooden-boxes", name: "Wooden Keepsake Boxes" },
      { slug: "wooden-cross", name: "Wooden Cross Pendant" },
      { slug: "game", name: "Nautical Dice & Card Game" },
      { slug: "mirror", name: "Nautical Porthole Mirror" },
      { slug: "home-kitchen", name: "Brass Kitchen Décor Set" },
      { slug: "home-appliances", name: "Nautical Home Accents" },
      { slug: "crystal-wood-crafts", name: "Crystal & Wood Desk Crafts" },
      { slug: "armillary", name: "Brass Armillary Sphere" },
    ],
  },
  {
    slug: "kitchen-product",
    name: "Kitchen Product",
    children: [
      { slug: "wooden-kitchen", name: "Wooden", children: kitchenTypes("wooden") },
      { slug: "brass-kitchen", name: "Brass", children: kitchenTypes("brass") },
    ],
  },
  {
    slug: "decor",
    name: "Décor",
    children: [
      { slug: "show-pieces", name: "Show Pieces" },
      { slug: "candle-holders", name: "Candle Holders" },
      { slug: "table-decor", name: "Table Decor" },
      { slug: "key-chain", name: "Key Chain" },
    ],
  },
  {
    slug: "jewellery",
    name: "Jewellery",
    children: [
      { slug: "bangles", name: "Bangles" },
      { slug: "bracelet", name: "Bracelet" },
      { slug: "bags-clutch", name: "Bags/Clutch" },
      { slug: "necklace", name: "Necklace" },
      { slug: "jewellery-boxes", name: "Jewellery Boxes" },
    ],
  },
  {
    slug: "hardware",
    name: "Hardware",
    children: [
      { slug: "brackets", name: "Brackets" },
      { slug: "door-handles", name: "Door Handles" },
      { slug: "hangers", name: "Hangers" },
      { slug: "knockers", name: "Knockers" },
      { slug: "locks-keys", name: "Locks & Keys" },
    ],
  },
  {
    slug: "modern-brass-wall-sconce",
    name: "Modern Brass Wall Sconce",
    children: [
      { slug: "brass-wall-sconce", name: "Brass" },
      { slug: "wooden-wall-sconce", name: "Wooden" },
    ],
  },
  {
    slug: "lighting-lamps",
    name: "Lighting lamps",
    children: [
      { slug: "ceiling-hanging-lights", name: "Ceiling & Hanging Lights" },
      { slug: "wall-lights", name: "Wall Lights" },
      { slug: "table-lamps", name: "Table Lamps" },
      { slug: "spot-lights", name: "Spot Lights" },
      { slug: "picture-lights", name: "Picture Lights" },
      { slug: "bathroom-lights", name: "Bathroom Lights" },
      { slug: "flush-mount", name: "Flush Mount" },
      { slug: "floor-lamp", name: "Floor Lamp" },
      { slug: "chandelier", name: "Chandelier" },
      { slug: "rechargeable-lamps", name: "Rechargeable Lamps" },
      { slug: "outdoor-lights", name: "Outdoor Lights" },
    ],
  },
];

function product(
  data: Pick<Product, "slug" | "name" | "sku" | "price" | "collection" | "image"> & Partial<Product>
): Product {
  const image = data.image;
  return {
    rating: 4.6,
    reviews: 32,
    stock: "in-stock",
    finish: "Antique / polished",
    material: data.material || "Brass / steel / wood",
    dimensions: data.dimensions || "As pictured",
    weight: "—",
    packaging: "Export carton",
    included: ["Product", "Export packing"],
    description: data.description || data.name,
    story: "Handcrafted for wholesale export from India. Logo and packaging programmes available.",
    moq: 12,
    ...data,
    image,
    gallery: data.gallery || [image],
  };
}

function listing(
  parent: string,
  sub: string,
  name: string,
  sku: string,
  price: number,
  collection: string,
  image: string
): Product {
  return product({
    slug: `${parent}-${sub}-1`,
    name,
    sku: `${sku}-01`,
    price,
    wholesaleFrom: Number((price * 0.68).toFixed(2)),
    moq: 12,
    collection,
    category: parent,
    subcategory: sub,
    image,
    description: `${name}. Handcrafted for export from our Roorkee factory — logo and packaging programmes available.`,
  });
}

function extra(
  parent: string,
  sub: string,
  n: number,
  name: string,
  sku: string,
  price: number,
  collection: string,
  image: string,
  gallery: string[]
): Product {
  return product({
    slug: `${parent}-${sub}-${n}`,
    name,
    sku,
    price,
    wholesaleFrom: Number((price * 0.68).toFixed(2)),
    collection,
    category: parent,
    subcategory: sub,
    image,
    gallery,
    description: `${name}. Handcrafted for export from our Roorkee factory — logo and packaging programmes available.`,
  });
}

const armor = [img.armor, img.knight, img.helmet, img.armor];
const helm = [img.helmet, img.knight, img.armor, img.helmet];
const glass = [img.telescope, img.telescopeNight, img.telescopeAstro, img.telescope];
const bins = [img.binoculars, img.binocularsField, img.binocularsMap, img.binoculars];
const comps = [img.compassBrass, img.compassGold, img.compassMap, img.compassBrass];
const lamps = [img.lanternCandle, img.lanternOil, img.lanternVintage, img.lanternCandle];
const time = [img.watch, img.clock, img.watch, img.clock];
const bells = [img.antiques6, img.lanternVintage, img.ship, img.rope];
const wood = [img.workshop, img.gift, img.jewelry, img.globe];
const tripods = [img.tripodWood, img.tripodSpyglass, img.tripodMarine, img.tripodWood];
const binTripods = [img.tripodBinocular, img.binoculars, img.binocularsMap, img.tripodBinocular];
const wheels = [img.shipWheelWood, img.sail, img.sailboat, img.ship];
const lampStands = [img.lampTripod, img.royalLamp, img.lanternVintage, img.lanternOil];

export const shopNowProducts: Product[] = [
  listing("brass-binocular", "handheld-brass-binocular", "Antique Field Binocular 6×30", "MM-BIN-HB", 36, "brass-binoculars", bins[0]),
  listing("brass-binocular", "officer-field-binocular", "Officer Leather Binocular 8×40", "MM-BIN-OF", 42, "brass-binoculars", bins[1]),
  listing("brass-binocular", "brass-handheld-binocular", "Polished Pocket Binocular 4×30", "MM-BIN-HH", 29, "brass-binoculars", bins[2]),
  listing("brass-spyglass-telescope", "leather-wrapped-spyglass", "Leather-Wrapped Handheld Spyglass", "MM-SPY-LW", 48, "telescopes", glass[1]),
  listing("brass-spyglass-telescope", "handheld-brass-spyglass", "Retractable Brass Pocket Spyglass", "MM-SPY-HH", 39, "telescopes", glass[0]),
  listing("brass-spyglass-telescope", "handheld-retractable-telescope", 'Marine Mini Spyglass 6"', "MM-TEL-HR", 4.95, "telescopes", glass[2]),
  listing("brass-telescope-stand", "tabletop-brass-telescope-stand", "Desk Telescope on Short Stand", "MM-STD-TT", 89, "telescopes", tripods[0]),
  listing("brass-telescope-stand", "tabletop-telescope-stand", "Tabletop Brass Telescope with Base", "MM-TEL-TT", 29, "telescopes", glass[0]),
  listing("brass-telescope-tripod", "floor-telescope", "Adjustable Floor Standing Telescope", "MM-TEL-FL", 79, "telescopes", tripods[2]),
  listing("brass-binocular-tripod", "brass-tripod-binocular", "Brass Observation Binocular on Tripod", "MM-BIN-TR", 48, "brass-binoculars", binTripods[0]),
  listing("brass-lamp-tripod", "marine-brass-lamp-tripod", "Marine Oil Lamp on Wooden Tripod", "MM-LMP-TR", 72, "nautical-decor", lampStands[0]),
  listing("wooden-ship-wheel", "handmade-wooden-ship-wheel", 'Handmade Teak Ship Wheel 18"', "MM-WHL-WD", 54, "ship-wheels", wheels[0]),
  listing("royal-lamp-tripod", "royal-brass-lamp-tripod", "Royal Brass Floor Lamp on Tripod", "MM-LMP-RY", 86, "nautical-decor", lampStands[1]),
  listing("armor-breast-plate", "gloves", "Steel Armor Combat Gloves", "MM-GLV", 24, "nautical-decor", armor[0]),
  listing("armor-helmets", "roman-centurion-helmet", "Roman Centurion Helmet with Plume", "MM-HLM-RC", 79, "nautical-decor", helm[0]),
  listing("armor-helmets", "armor-shield", "Heraldic Knight Shield", "MM-HLM-SH", 35, "nautical-decor", armor[1]),
  listing("armor-helmets", "norman-knight-helmet", "Norman Knight Nasal Helmet", "MM-HLM-NK", 88, "nautical-decor", helm[1]),
  listing("armor-helmets", "movie-replica-armor-helmet", "Movie Replica Armor Helmet", "MM-HLM-MV", 95, "nautical-decor", helm[2]),
  listing("armor-helmets", "corinthian-armor-helmet", "Corinthian Greek Helmet", "MM-HLM-CO", 82, "nautical-decor", helm[0]),
  listing("armor-helmets", "german-armor-helmet", "German Sallet Helmet", "MM-HLM-GE", 86, "nautical-decor", helm[1]),
  listing("armor-helmets", "roman-armor-helmet", "Roman Legionary Helmet", "MM-HLM-RA", 79, "nautical-decor", helm[2]),
  listing("armor-helmets", "medieval-armor-helmet", "Medieval Great Helm", "MM-HLM-MD", 84, "nautical-decor", helm[0]),
  listing("muscle-armour", "steel-shield", "Solid Steel Battle Shield", "MM-MSC-SS", 42, "nautical-decor", armor[0]),
  listing("muscle-armour", "armour-shield", "Round Brass-Rimmed Shield", "MM-MSC-AS", 39, "nautical-decor", armor[1]),
  listing("muscle-armour", "muscle-armor", "Greek Muscle Cuirass", "MM-MSC-MA", 249, "nautical-decor", armor[2]),
  listing("muscle-armour", "leather-muscle-armor", "Leather Muscle Cuirass", "MM-MSC-LM", 189, "nautical-decor", armor[3]),
  listing("armory-props", "medieval-shield", "Medieval Heater Shield", "MM-PRP-MS", 32, "nautical-decor", armor[1]),
  listing("armory-props", "chainmail-armor", "Chainmail Hauberk", "MM-PRP-CM", 110, "nautical-decor", armor[0]),
  listing("armory-props", "roman-legion-belt", "Roman Legion Cingulum Belt", "MM-PRP-BL", 28, "nautical-decor", helm[2]),
  listing("armory-props", "armor-shoes-sandals", "Roman Armor Caligae Sandals", "MM-PRP-SH", 36, "nautical-decor", armor[2]),
  listing("armory-props", "armor-gauntlet", "Steel Armor Gauntlet", "MM-PRP-GT", 39, "nautical-decor", helm[0]),
  listing("armory-props", "armor-hand-leg-guard", "Armor Vambrace & Greave Set", "MM-PRP-HG", 44, "nautical-decor", armor[1]),
  listing("armory-props", "armor-shoulder", "Armor Pauldron Shoulder Guard", "MM-PRP-SD", 41, "nautical-decor", armor[0]),
  listing("compass", "push-button-compass", "Push-Button Pocket Compass", "MM-CMP-PB", 5.5, "brass-compasses", comps[0]),
  listing("compass", "compass-with-lid", "Hinged-Lid Desk Compass", "MM-CMP-LD", 6.5, "brass-compasses", comps[1]),
  listing("compass", "flat-compass", "Flat Card Compass", "MM-CMP-FL", 4.8, "brass-compasses", comps[2]),
  listing("compass", "brunton-compass", "Brunton Survey Compass", "MM-CMP-BR", 12, "brass-compasses", comps[3]),
  listing("compass", "sundial-compass", "Brass Sundial Compass", "MM-CMP-SD", 14, "brass-compasses", comps[0]),
  listing("spotlight-searchlight", "table-lamp", "Brass Cabin Table Lamp", "MM-LGT-TL", 22, "nautical-decor", lamps[0]),
  listing("spotlight-searchlight", "spot-light", "Marine Deck Spot Light", "MM-LGT-SP", 28, "nautical-decor", lamps[1]),
  listing("spotlight-searchlight", "spotlight", "Brass Bulkhead Searchlight", "MM-LGT-SL", 32, "nautical-decor", lamps[2]),
  listing("spotlight-searchlight", "floor-lamp", "Nautical Floor Lantern", "MM-LGT-FL", 45, "nautical-decor", lamps[3]),
  listing("clocks", "pocket-watches", "Brass Open-Face Pocket Watch", "MM-CLK-PW", 18, "nautical-instruments", time[0]),
  listing("clocks", "table-clocks", "Maritime Desk Clock", "MM-CLK-TC", 22, "nautical-instruments", time[1]),
  listing("clocks", "brass-table-watch", "Brass Table Watch with Compass Dial", "MM-CLK-TW", 26, "nautical-instruments", time[2]),
  listing("clocks", "nautical-pocket-watch", "Nautical Pocket Watch on Chain", "MM-CLK-NP", 21, "nautical-instruments", time[3]),
  listing("ship-bell", "hand-bell", "Brass Hand Bell", "MM-BEL-HN", 16, "nautical-decor", bells[0]),
  listing("ship-bell", "hanging-bell", "Hanging Ship Bell with Bracket", "MM-BEL-HG", 22, "nautical-decor", bells[1]),
  listing("ship-bell", "desk-bell", "Captain’s Desk Bell", "MM-BEL-DK", 14, "nautical-decor", bells[2]),
  listing("nautical-decor-gifts", "brass-burner", "Brass Incense Burner", "MM-DEC-BR", 18, "nautical-decor", wood[0]),
  listing("nautical-decor-gifts", "pen-holder", "Brass Desk Pen Holder", "MM-DEC-PH", 8, "nautical-decor", wood[1]),
  listing("nautical-decor-gifts", "wooden-mug", "Turned Wooden Tankard", "MM-DEC-MG", 7, "nautical-decor", wood[2]),
  listing("nautical-decor-gifts", "wooden-game", "Wooden Chess & Board Game", "MM-DEC-WG", 15, "nautical-decor", wood[3]),
  listing("nautical-decor-gifts", "wooden-boxes", "Wooden Keepsake Boxes", "MM-DEC-BX", 12, "nautical-decor", wood[0]),
  listing("nautical-decor-gifts", "wooden-cross", "Wooden Cross Pendant", "MM-DEC-CR", 2.2, "nautical-decor", img.jewelry),
  listing("nautical-decor-gifts", "game", "Nautical Dice & Card Game", "MM-DEC-GM", 11, "nautical-decor", wood[1]),
  listing("nautical-decor-gifts", "mirror", "Nautical Porthole Mirror", "MM-DEC-MR", 28, "nautical-decor", img.lighthouse),
  listing("nautical-decor-gifts", "home-kitchen", "Brass Kitchen Décor Set", "MM-DEC-HK", 16, "nautical-decor", wood[2]),
  listing("nautical-decor-gifts", "home-appliances", "Nautical Home Accents", "MM-DEC-HA", 19, "nautical-decor", wood[3]),
  listing("nautical-decor-gifts", "crystal-wood-crafts", "Crystal & Wood Desk Crafts", "MM-DEC-CW", 24, "nautical-decor", wood[0]),
  listing("nautical-decor-gifts", "armillary", "Brass Armillary Sphere", "MM-DEC-AR", 39, "nautical-instruments", img.globe),
  { ...listing("kitchen-product", "wooden-kitchen", "Hand-Carved Wooden Kitchen Board", "MM-KIT-WD", 14, "nautical-decor", wood[0]), subcategory: "wooden-servewares" },
  { ...listing("kitchen-product", "brass-kitchen", "Solid Brass Kitchen Serving Set", "MM-KIT-BR", 22, "nautical-decor", lamps[2]), subcategory: "brass-servewares" },
  listing("decor", "show-pieces", "Brass Showpiece Sculpture", "MM-DCR-SP", 36, "nautical-decor", img.globe),
  listing("decor", "candle-holders", "Antique Brass Candle Holder", "MM-DCR-CH", 18, "nautical-decor", lamps[0]),
  listing("decor", "table-decor", "Brass Table Decor Set", "MM-DCR-TD", 16, "nautical-decor", img.decorOffice),
  listing("decor", "key-chain", "Brass Key Chain", "MM-DCR-KC", 3.5, "nautical-decor", comps[1]),
  product({
    slug: "ashok-stambh-1",
    name: "Ashok Stambh Table Décor",
    sku: "MM-DCR-AS-01",
    price: 22,
    wholesaleFrom: 14,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.decorAshok,
    gallery: [img.decorAshok, img.decorOffice, img.globe],
    description: "Brass Ashok Stambh for office desks and table décor.",
  }),
  product({
    slug: "office-compass-1",
    name: "Brass Desk Compass",
    sku: "MM-DCR-CP-01",
    price: 18,
    wholesaleFrom: 12,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.compassBrass,
    gallery: [img.compassBrass, img.compassGold, img.decorOffice],
    description: "Table compass for office décor and executive gifting.",
  }),
  product({
    slug: "office-flag-1",
    name: "Desk Flag Stand",
    sku: "MM-DCR-FG-01",
    price: 14,
    wholesaleFrom: 9,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.decorFlag,
    gallery: [img.decorFlag, img.decorOffice, img.workshop],
    description: "Brass desk flag stand for office and table décor.",
  }),
  product({
    slug: "flower-vase-1",
    name: "Brass Flower Vase",
    sku: "MM-DCR-FV-01",
    price: 19,
    wholesaleFrom: 12,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.decorVase,
    gallery: [img.decorVase, img.decorUrli, img.serveBowl],
    description: "Brass flower vase for table and office décor.",
  }),
  product({
    slug: "ink-pot-1",
    name: "Brass Ink Pot",
    sku: "MM-DCR-IP-01",
    price: 11,
    wholesaleFrom: 7,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.antiques5,
    gallery: [img.antiques5, img.decorOffice, img.workshop],
    description: "Desk ink pot in brass — a classic office table accent.",
  }),
  product({
    slug: "kalpvriksha-1",
    name: "Kalpvriksha Table Décor",
    sku: "MM-DCR-KV-01",
    price: 27,
    wholesaleFrom: 18,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.workshop,
    gallery: [img.workshop, img.decorAshok, img.globe],
    description: "Kalpvriksha brass tree for office and table décor.",
  }),
  product({
    slug: "paper-weight-1",
    name: "Brass Paper Weight",
    sku: "MM-DCR-PW-01",
    price: 8,
    wholesaleFrom: 5,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.antiques3,
    gallery: [img.antiques3, img.decorOffice, img.workshop],
    description: "Solid brass paper weight for desks and office décor.",
  }),
  product({
    slug: "sand-clock-1",
    name: "Brass Sand Clock",
    sku: "MM-DCR-SC-01",
    price: 16,
    wholesaleFrom: 10,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.hourglass,
    gallery: [img.hourglass, img.hourglassSand, img.clock],
    description: "Sand clock / hourglass for table décor.",
  }),
  product({
    slug: "table-clock-1",
    name: "Brass Table Clock",
    sku: "MM-DCR-TC-01",
    price: 21,
    wholesaleFrom: 14,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.clock,
    gallery: [img.clock, img.watch, img.hourglass],
    description: "Brass table clock for office desks and décor sets.",
  }),
  product({
    slug: "taj-mahal-1",
    name: "Taj Mahal Showpiece",
    sku: "MM-DCR-TJ-01",
    price: 44,
    wholesaleFrom: 29,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "show-pieces",
    image: img.decorTaj,
    gallery: [img.decorTaj, img.decorAshok, img.globe],
    description: "Brass Taj Mahal showpiece for home and gift programmes.",
  }),
  product({
    slug: "bangles-1",
    name: "Handcrafted Brass Bangles",
    sku: "MM-JWL-BG-01",
    price: 8,
    wholesaleFrom: 5.5,
    collection: "nautical-decor",
    category: "jewellery",
    subcategory: "bangles",
    image: img.jewelryBangle,
    gallery: [img.jewelryBangle, img.jewelryBracelet, img.jewelryNecklace],
    description: "Handcrafted brass bangles — polished and antique finishes for retail and wholesale.",
  }),
  product({
    slug: "bracelet-1",
    name: "Antique Brass Bracelet",
    sku: "MM-JWL-BR-01",
    price: 9.5,
    wholesaleFrom: 6.5,
    collection: "nautical-decor",
    category: "jewellery",
    subcategory: "bracelet",
    image: img.jewelryBracelet,
    gallery: [img.jewelryBracelet, img.jewelryBangle, img.jewelryNecklace],
    description: "Antique-finish brass bracelet for jewellery programmes and gifting.",
  }),
  product({
    slug: "bags-clutch-1",
    name: "Brass-Clasp Evening Clutch",
    sku: "MM-JWL-CL-01",
    price: 28,
    wholesaleFrom: 18,
    collection: "nautical-decor",
    category: "jewellery",
    subcategory: "bags-clutch",
    image: img.jewelryBag,
    gallery: [img.jewelryBag, img.gift, img.jewelryBox],
    description: "Evening bag / clutch with brass clasp — a jewellery-adjacent gift piece.",
  }),
  product({
    slug: "necklace-1",
    name: "Statement Brass Necklace",
    sku: "MM-JWL-NK-01",
    price: 12,
    wholesaleFrom: 8,
    collection: "nautical-decor",
    category: "jewellery",
    subcategory: "necklace",
    image: img.jewelryNecklace,
    gallery: [img.jewelryNecklace, img.jewelryBangle, img.jewelryBracelet],
    description: "Statement brass necklace for retail counters and export jewellery lots.",
  }),
  product({
    slug: "jewellery-boxes-1",
    name: "Jewellery Box",
    sku: "MM-JWL-BX-01",
    price: 19,
    wholesaleFrom: 12,
    collection: "nautical-decor",
    category: "jewellery",
    subcategory: "jewellery-boxes",
    image: img.jewelryBox,
    gallery: [img.jewelryBox, img.gift, img.workshop],
    description: "Jewellery box with brass inlay — for sets, gifting and wholesale packing.",
  }),
  listing("hardware", "brackets", "Solid Brass Wall Bracket", "MM-HDW-BK", 11, "nautical-decor", wood[2]),
  listing("hardware", "door-handles", "Antique Brass Door Handle", "MM-HDW-DH", 15, "nautical-decor", wood[0]),
  listing("hardware", "hangers", "Brass Coat Hanger Hook", "MM-HDW-HG", 7.5, "nautical-decor", wood[3]),
  listing("hardware", "knockers", "Lion Head Door Knocker", "MM-HDW-KN", 21, "nautical-decor", img.antiques5),
  listing("hardware", "locks-keys", "Brass Lock & Skeleton Key Set", "MM-HDW-LK", 13, "nautical-decor", img.antiques3),
  product({
    slug: "fluted-ceramic-wall-sconce",
    name: "Fluted Ceramic Wall Sconce",
    sku: "MM-WSC-FL-01",
    price: 48,
    wholesaleFrom: 32,
    collection: "modern-brass-wall-sconce",
    category: "modern-brass-wall-sconce",
    subcategory: "brass-wall-sconce",
    finish: "Glazed ceramic & polished brass",
    material: "Ceramic shade, solid brass finial",
    image: "/sconce-fluted.jpg",
    gallery: ["/sconce-fluted.jpg", "/sconce-dome.jpg", "/sconce-cone.jpg"],
    description:
      "Pair of fluted ceramic wall sconces with a polished brass ball finial. A sculptural modern light for halls, hotels and dining rooms.",
  }),
  product({
    slug: "arched-dome-brass-wall-sconce",
    name: "Arched Dome Brass Wall Sconce",
    sku: "MM-WSC-DM-01",
    price: 54,
    wholesaleFrom: 36,
    collection: "modern-brass-wall-sconce",
    category: "modern-brass-wall-sconce",
    subcategory: "brass-wall-sconce",
    finish: "Antique brass & opal glass",
    material: "Solid brass arm, opal glass dome",
    image: "/sconce-dome.jpg",
    gallery: ["/sconce-dome.jpg", "/sconce-cone.jpg", "/sconce-fluted.jpg"],
    description:
      "Arched brass wall sconce with a warm opal dome shade. Soft downward light for bedrooms, corridors and hospitality interiors.",
  }),
  product({
    slug: "cone-brass-wall-sconce",
    name: "Cone Brass Wall Sconce",
    sku: "MM-WSC-CN-01",
    price: 52,
    wholesaleFrom: 34,
    collection: "modern-brass-wall-sconce",
    category: "modern-brass-wall-sconce",
    subcategory: "brass-wall-sconce",
    finish: "Brushed antique brass",
    material: "Solid brass cone shade and backplate",
    image: "/sconce-cone.jpg",
    gallery: ["/sconce-cone.jpg", "/sconce-dome.jpg", "/sconce-fluted.jpg"],
    description:
      "Cone brass wall sconce on a curved arm — compact, warm and export-ready for modern interiors and hotel programmes.",
  }),
  ...[
    { slug: "fluted", name: "Wooden Fluted Wall Sconce", image: "/sconce-fluted.jpg", price: 44 },
    { slug: "dome", name: "Walnut Arched Dome Wall Sconce", image: "/sconce-dome.jpg", price: 49 },
    { slug: "cone", name: "Teak Cone Wall Sconce", image: "/sconce-cone.jpg", price: 46 },
  ].map((s, i) =>
    product({
      slug: `wooden-${s.slug}-wall-sconce`,
      name: s.name,
      sku: `MM-WSC-WD-0${i + 1}`,
      price: s.price,
      wholesaleFrom: Number((s.price * 0.68).toFixed(2)),
      collection: "modern-brass-wall-sconce",
      category: "modern-brass-wall-sconce",
      subcategory: "wooden-wall-sconce",
      finish: "Natural wood & antique brass",
      material: "Hand-turned hardwood arm, brass fittings",
      image: s.image,
      gallery: [s.image, "/sconce-dome.jpg", "/sconce-cone.jpg", "/sconce-fluted.jpg"].filter((g, j, a) => a.indexOf(g) === j),
      description: `${s.name} with a hand-turned hardwood arm and brass fittings — warm modern lighting for homes, hotels and hospitality projects.`,
    })
  ),
  listing("lighting-lamps", "ceiling-hanging-lights", "Brass Ceiling Hanging Light", "MM-LL-CH", 68, "lighting-lamps", img.lightCeiling),
  listing("lighting-lamps", "wall-lights", "Antique Brass Wall Light", "MM-LL-WL", 42, "lighting-lamps", img.lightWall),
  listing("lighting-lamps", "table-lamps", "Brass Table Lamp", "MM-LL-TL", 38, "lighting-lamps", img.lightTable),
  listing("lighting-lamps", "spot-lights", "Brass Spot Light", "MM-LL-SP", 29, "lighting-lamps", img.lightSpot),
  listing("lighting-lamps", "picture-lights", "Brass Picture Light", "MM-LL-PL", 34, "lighting-lamps", img.lightPicture),
  listing("lighting-lamps", "bathroom-lights", "Brass Bathroom Light", "MM-LL-BT", 46, "lighting-lamps", img.lightBathroom),
  listing("lighting-lamps", "flush-mount", "Brass Flush Mount Light", "MM-LL-FM", 52, "lighting-lamps", img.lightFlush),
  listing("lighting-lamps", "floor-lamp", "Brass Floor Lamp", "MM-LL-FL", 89, "lighting-lamps", img.lightFloor),
  listing("lighting-lamps", "chandelier", "Brass Chandelier", "MM-LL-CD", 165, "lighting-lamps", img.lightChandelier),
  listing("lighting-lamps", "rechargeable-lamps", "Rechargeable Brass Table Lamp", "MM-LL-RC", 36, "lighting-lamps", img.lightRecharge),
  listing("lighting-lamps", "outdoor-lights", "Brass Outdoor Light", "MM-LL-OD", 58, "lighting-lamps", img.lightOutdoor),
  product({
    slug: "vintage-brass-telescope-wooden-tripod",
    name: "Vintage Telescope on Wooden Tripod",
    sku: "MM-TEL-TR-01",
    price: 189,
    wholesaleFrom: 129,
    moq: 4,
    rating: 4.8,
    reviews: 64,
    collection: "telescopes",
    category: "brass-telescope-tripod",
    subcategory: "vintage-brass-telescope-wood-tripod",
    finish: "Antique brass, leather wrap",
    material: "Solid brass, genuine leather, hardwood tripod",
    dimensions: 'Floor standing · 36"–60" adjustable',
    featured: true,
    image: img.tripodWood,
    gallery: [img.tripodWood, img.tripodSpyglass, img.telescope],
    description:
      "A floor-standing vintage brass telescope with leather wrap and a hardwood tripod. Built for actual viewing and for nautical interiors, hotels and wholesale display.",
  }),
  product({
    slug: "vintage-brass-nautical-spyglass-tripod",
    name: "Nautical Spyglass on Studio Tripod",
    sku: "MM-TEL-TR-02",
    price: 198,
    wholesaleFrom: 138,
    moq: 4,
    rating: 4.7,
    reviews: 41,
    collection: "telescopes",
    category: "brass-telescope-tripod",
    subcategory: "nautical-spyglass-tripod",
    finish: "Polished nickel / antique brass",
    material: "Brass barrel, optical glass, hardwood tripod",
    dimensions: 'Floor standing · 40"–62" adjustable',
    featured: true,
    image: img.tripodSpyglass,
    gallery: [img.tripodSpyglass, img.tripodWood, img.telescopeNight],
    description:
      "Nautical spyglass on a studio tripod — a presentation piece for showrooms and a working instrument for collectors.",
  }),
  product({
    slug: "handcrafted-brass-binocular-telescope-tripod",
    name: "Dual-Head Binocular on Wooden Tripod",
    sku: "MM-BIN-TR-01",
    price: 245,
    wholesaleFrom: 168,
    moq: 2,
    rating: 4.9,
    reviews: 38,
    collection: "brass-binoculars",
    category: "brass-binocular-tripod",
    subcategory: "binocular-telescope-wood-tripod",
    finish: "Polished brass",
    material: "Solid brass binocular head, hardwood tripod",
    dimensions: 'Floor standing · dual 20×80 style head',
    featured: true,
    image: img.tripodBinocular,
    gallery: [img.tripodBinocular, img.binoculars, img.binocularsMap],
    description:
      "Handcrafted brass binocular telescope on a wooden tripod — dual optics for viewing and a statement piece for lobbies and trade floors.",
  }),
  product({
    slug: "vintage-style-brass-marine-telescope-tripod",
    name: "Marine Telescope on Brass Tripod",
    sku: "MM-TEL-TR-03",
    price: 219,
    wholesaleFrom: 158,
    moq: 4,
    rating: 4.8,
    reviews: 52,
    collection: "telescopes",
    category: "brass-telescope-tripod",
    subcategory: "marine-telescope-brass-tripod",
    finish: "Full polished brass",
    material: "Solid brass barrel and tripod, optical glass",
    dimensions: 'Floor standing · 42"–64" adjustable',
    featured: true,
    image: img.tripodMarine,
    gallery: [img.tripodMarine, img.tripodWood, img.telescope],
    description:
      "Full-brass marine telescope on a matching brass tripod. Export-ready for retailers, hotels and nautical collections.",
  }),
  { ...extra("kitchen-product", "wooden-kitchen", 2, "Wooden Serving Spoon Set", "MM-KIT-WD-02", 11, "nautical-decor", img.serveTray, [img.serveTray, img.storageBox, img.cutleryTable]), subcategory: "wooden-cutleries" },
  { ...extra("kitchen-product", "wooden-kitchen", 3, "Carved Wooden Spice Box", "MM-KIT-WD-03", 16, "nautical-decor", img.storageBox, [img.storageBox, img.servePottery, img.workshop]), subcategory: "wooden-storage-wares" },
  extra("kitchen-product", "wooden-cookware", 1, "Wooden Cooking Spatula Set", "MM-KIT-WD-04", 12, "nautical-decor", img.servePottery, [img.servePottery, img.cutleryGold, img.storageJar]),
  extra("kitchen-product", "wooden-drinkware", 1, "Turned Wooden Tankard Mug", "MM-KIT-WD-05", 15, "nautical-decor", img.drinkwareCup, [img.drinkwareCup, img.drinkwareCoffee, img.woodenKitchen]),
  extra("kitchen-product", "wooden-tea-strainer-infuser", 1, "Wooden Handle Tea Strainer", "MM-KIT-WD-06", 8, "nautical-decor", img.teaStrainer, [img.teaStrainer, img.teaInfuser, img.drinkwareTea]),
  { ...extra("kitchen-product", "brass-kitchen", 2, "Brass Kitchen Ladle Set", "MM-KIT-BR-02", 19, "nautical-decor", img.cutleryGold, [img.cutleryGold, img.serveBowl, lamps[2]]), subcategory: "brass-cutleries" },
  { ...extra("kitchen-product", "brass-kitchen", 3, "Brass Cookware Kadhai", "MM-KIT-BR-03", 32, "nautical-decor", img.servePottery, [img.servePottery, img.serveBowl, img.cutlerySet]), subcategory: "brass-cookware" },
  extra("kitchen-product", "brass-drinkware", 1, "Hammered Brass Tumbler Set", "MM-KIT-BR-04", 24, "nautical-decor", img.drinkwareTea, [img.drinkwareTea, img.drinkwareCup, img.cutleryGold]),
  extra("kitchen-product", "brass-storage-wares", 1, "Brass Storage Canister", "MM-KIT-BR-05", 27, "nautical-decor", img.storageCanister, [img.storageCanister, img.storageJar, img.serveBowl]),
  extra("kitchen-product", "brass-tea-strainer-infuser", 1, "Brass Tea Infuser", "MM-KIT-BR-06", 9, "nautical-decor", img.teaInfuser, [img.teaInfuser, img.teaStrainer, img.teaPot]),
  extra("decor", "candle-holders", 2, "Brass Pillar Candle Stand", "MM-DCR-CH-02", 16, "nautical-decor", lamps[1], [lamps[1], lamps[2], img.lanternCandle]),
  extra("decor", "candle-holders", 3, "Twin-Arm Candle Holder", "MM-DCR-CH-03", 22, "nautical-decor", lamps[2], [lamps[2], lamps[0], img.lanternVintage]),
  extra("decor", "key-chain", 2, "Antique Brass Key Fob", "MM-DCR-KC-02", 4, "nautical-decor", comps[0], [comps[0], comps[2], img.watch]),
  extra("decor", "key-chain", 3, "Ship-Wheel Key Chain", "MM-DCR-KC-03", 4.5, "nautical-decor", img.shipWheelWood, [img.shipWheelWood, comps[1], img.rope]),
  extra("decor", "show-pieces", 2, "Brass Animal Showpiece", "MM-DCR-SP-02", 33, "nautical-decor", img.decorAnimal, [img.decorAnimal, img.globe, img.decorTaj]),
  extra("jewellery", "bangles", 2, "Antique Pair of Bangles", "MM-JWL-BG-02", 10, "nautical-decor", img.jewelryBracelet, [img.jewelryBracelet, img.jewelryBangle, img.jewelryGold]),
  extra("jewellery", "bangles", 3, "Polished Brass Bangle Set", "MM-JWL-BG-03", 12, "nautical-decor", img.jewelryGold, [img.jewelryGold, img.jewelryBangle, img.jewelryNecklace]),
  extra("jewellery", "bracelet", 2, "Link Brass Bracelet", "MM-JWL-BR-02", 11, "nautical-decor", img.jewelryGold, [img.jewelryGold, img.jewelryBracelet, img.jewelryBangle]),
  extra("jewellery", "bracelet", 3, "Brass Cuff Bracelet", "MM-JWL-BR-03", 13, "nautical-decor", img.jewelryBangle, [img.jewelryBangle, img.jewelryBracelet, img.jewelry]),
  extra("jewellery", "bags-clutch", 2, "Embroidered Evening Clutch", "MM-JWL-CL-02", 32, "nautical-decor", img.gift, [img.gift, img.jewelryBag, img.jewelryBox]),
  extra("jewellery", "bags-clutch", 3, "Brass-Frame Potli Bag", "MM-JWL-CL-03", 24, "nautical-decor", img.jewelryBox, [img.jewelryBox, img.jewelryBag, img.gift]),
  extra("jewellery", "necklace", 2, "Brass Pendant Necklace", "MM-JWL-NK-02", 14, "nautical-decor", img.jewelryGold, [img.jewelryGold, img.jewelryNecklace, img.jewelry]),
  extra("jewellery", "necklace", 3, "Layered Brass Necklace", "MM-JWL-NK-03", 16, "nautical-decor", img.jewelry, [img.jewelry, img.jewelryNecklace, img.jewelryBangle]),
  extra("jewellery", "jewellery-boxes", 2, "Travel Jewellery Case", "MM-JWL-BX-02", 22, "nautical-decor", img.gift, [img.gift, img.jewelryBox, img.workshop]),
  extra("jewellery", "jewellery-boxes", 3, "Inlaid Ring Box", "MM-JWL-BX-03", 11, "nautical-decor", img.workshop, [img.workshop, img.jewelryBox, img.gift]),
  extra("hardware", "brackets", 2, "Corner Shelf Bracket", "MM-HDW-BK-02", 9, "nautical-decor", wood[0], [wood[0], wood[2], img.workshop]),
  extra("hardware", "brackets", 3, "Heavy-Duty L Bracket", "MM-HDW-BK-03", 13, "nautical-decor", img.workshop, [img.workshop, wood[2], img.antiques3]),
  extra("hardware", "door-handles", 2, "Mortice Door Handle Pair", "MM-HDW-DH-02", 18, "nautical-decor", wood[1], [wood[1], wood[0], img.antiques]),
  extra("hardware", "door-handles", 3, "Brass Pull Handle Bar", "MM-HDW-DH-03", 16, "nautical-decor", img.antiques, [img.antiques, wood[0], img.workshop]),
  extra("hardware", "hangers", 2, "Wall Coat Hook Pair", "MM-HDW-HG-02", 8, "nautical-decor", img.rope, [img.rope, wood[3], img.workshop]),
  extra("hardware", "hangers", 3, "Brass Robe Hanger", "MM-HDW-HG-03", 9, "nautical-decor", wood[2], [wood[2], img.rope, wood[3]]),
  extra("hardware", "knockers", 2, "Ring Door Knocker", "MM-HDW-KN-02", 19, "nautical-decor", img.antiques4, [img.antiques4, img.antiques5, img.ship]),
  extra("hardware", "knockers", 3, "Anchor Door Knocker", "MM-HDW-KN-03", 23, "nautical-decor", img.ship, [img.ship, img.antiques5, img.rope]),
  extra("hardware", "locks-keys", 2, "Brass Padlock with Key", "MM-HDW-LK-02", 11, "nautical-decor", img.antiques5, [img.antiques5, img.antiques3, img.clock]),
  extra("hardware", "locks-keys", 3, "Antique Rim Lock Set", "MM-HDW-LK-03", 17, "nautical-decor", img.clock, [img.clock, img.antiques3, img.workshop]),
  extra("lighting-lamps", "ceiling-hanging-lights", 2, "Cluster Hanging Light", "MM-LL-CH-02", 74, "lighting-lamps", img.lightCeiling2, [img.lightCeiling2, img.lightCeiling, img.lightCeiling3]),
  extra("lighting-lamps", "ceiling-hanging-lights", 3, "Dome Ceiling Hanging Light", "MM-LL-CH-03", 62, "lighting-lamps", img.lightCeiling3, [img.lightCeiling3, img.lightCeiling, img.lightChandelier]),
  extra("lighting-lamps", "wall-lights", 2, "Swing-Arm Wall Light", "MM-LL-WL-02", 44, "lighting-lamps", img.lightWall2, [img.lightWall2, img.lightWall, img.lightWall3]),
  extra("lighting-lamps", "wall-lights", 3, "Glass-Shade Wall Light", "MM-LL-WL-03", 48, "lighting-lamps", img.lightWall3, [img.lightWall3, img.lightWall, "/sconce-dome.jpg"]),
  extra("lighting-lamps", "table-lamps", 2, "Cabin Brass Table Lamp", "MM-LL-TL-02", 41, "lighting-lamps", img.lightTable2, [img.lightTable2, img.lightTable, img.lightTable3]),
  extra("lighting-lamps", "table-lamps", 3, "Desk Brass Table Lamp", "MM-LL-TL-03", 35, "lighting-lamps", img.lightTable3, [img.lightTable3, img.lightTable, img.lanternVintage]),
  extra("lighting-lamps", "spot-lights", 2, "Adjustable Brass Spot Light", "MM-LL-SP-02", 32, "lighting-lamps", img.lightSpot2, [img.lightSpot2, img.lightSpot, img.lightSpot3]),
  extra("lighting-lamps", "spot-lights", 3, "Bulkhead Spot Light", "MM-LL-SP-03", 36, "lighting-lamps", img.lightSpot3, [img.lightSpot3, img.lightSpot, img.lanternOil]),
  extra("lighting-lamps", "picture-lights", 2, "Gallery Picture Light", "MM-LL-PL-02", 31, "lighting-lamps", img.lightPicture2, [img.lightPicture2, img.lightPicture, img.lightPicture3]),
  extra("lighting-lamps", "picture-lights", 3, "Slim Brass Picture Light", "MM-LL-PL-03", 28, "lighting-lamps", img.lightPicture3, [img.lightPicture3, img.lightPicture, img.lightWall]),
  extra("lighting-lamps", "bathroom-lights", 2, "Vanity Bathroom Light", "MM-LL-BT-02", 49, "lighting-lamps", img.lightBathroom2, [img.lightBathroom2, img.lightBathroom, img.lightBathroom3]),
  extra("lighting-lamps", "bathroom-lights", 3, "Bar Bathroom Light", "MM-LL-BT-03", 44, "lighting-lamps", img.lightBathroom3, [img.lightBathroom3, img.lightBathroom, img.lightFlush]),
  extra("lighting-lamps", "flush-mount", 2, "Low-Profile Flush Mount", "MM-LL-FM-02", 48, "lighting-lamps", img.lightFlush2, [img.lightFlush2, img.lightFlush, img.lightFlush3]),
  extra("lighting-lamps", "flush-mount", 3, "Dome Flush Mount Light", "MM-LL-FM-03", 55, "lighting-lamps", img.lightFlush3, [img.lightFlush3, img.lightFlush, img.lightCeiling]),
  extra("lighting-lamps", "floor-lamp", 2, "Tripod Brass Floor Lamp", "MM-LL-FL-02", 96, "lighting-lamps", img.lightFloor2, [img.lightFloor2, img.lightFloor, img.lightFloor3]),
  extra("lighting-lamps", "floor-lamp", 3, "Arc Brass Floor Lamp", "MM-LL-FL-03", 112, "lighting-lamps", img.lightFloor3, [img.lightFloor3, img.lightFloor, img.lightTable]),
  extra("lighting-lamps", "chandelier", 2, "Six-Arm Brass Chandelier", "MM-LL-CD-02", 198, "lighting-lamps", img.lightChandelier2, [img.lightChandelier2, img.lightChandelier, img.lightChandelier3]),
  extra("lighting-lamps", "chandelier", 3, "Small Entry Chandelier", "MM-LL-CD-03", 142, "lighting-lamps", img.lightChandelier3, [img.lightChandelier3, img.lightChandelier, img.lightCeiling3]),
  extra("lighting-lamps", "rechargeable-lamps", 2, "Cordless Rechargeable Lamp", "MM-LL-RC-02", 32, "lighting-lamps", img.lightRecharge2, [img.lightRecharge2, img.lightRecharge, img.lightRecharge3]),
  extra("lighting-lamps", "rechargeable-lamps", 3, "Portable Rechargeable Lamp", "MM-LL-RC-03", 29, "lighting-lamps", img.lightRecharge3, [img.lightRecharge3, img.lightRecharge, img.lightTable]),
  extra("lighting-lamps", "outdoor-lights", 2, "Porch Outdoor Light", "MM-LL-OD-02", 54, "lighting-lamps", img.lightOutdoor2, [img.lightOutdoor2, img.lightOutdoor, img.lightOutdoor3]),
  extra("lighting-lamps", "outdoor-lights", 3, "Garden Outdoor Light", "MM-LL-OD-03", 61, "lighting-lamps", img.lightOutdoor3, [img.lightOutdoor3, img.lightOutdoor, img.lanternVintage]),
];

function findChild(slug: string) {
  for (const parent of shopNowTree) {
    for (const child of parent.children) {
      if (child.slug === slug) return { parent, child, leaf: null };
      const leaf = child.children?.find((l) => l.slug === slug);
      if (leaf) return { parent, child, leaf };
    }
  }
  return null;
}

export function findShopNowLabel(slug: string | null) {
  if (!slug) return "Shop Now";
  const parent = shopNowTree.find((p) => p.slug === slug);
  if (parent) return parent.name;
  const hit = findChild(slug);
  if (!hit) return "Shop Now";
  return hit.leaf ? `${hit.child.name} ${hit.leaf.name}` : hit.child.name;
}

export function shopNowSubtree(slug: string) {
  const hit = findChild(slug);
  if (!hit || hit.leaf) return [slug];
  return [slug, ...(hit.child.children ?? []).map((l) => l.slug)];
}
