import type { Product } from "./products";
import { img } from "./images";

export type ShopNowChild = { slug: string; name: string };
export type ShopNowParent = {
  slug: string;
  name: string;
  children: ShopNowChild[];
};

export const shopNowTree: ShopNowParent[] = [
  {
    slug: "brass-binocular",
    name: "Handheld Brass Binoculars",
    children: [
      { slug: "handheld-brass-binocular", name: "Antique Field Binocular 6×30" },
      { slug: "officer-field-binocular", name: "Officer Leather Binocular 8×40" },
      { slug: "brass-handheld-binocular", name: "Polished Pocket Binocular 4×30" },
    ],
  },
  {
    slug: "brass-spyglass-telescope",
    name: "Brass Spyglasses",
    children: [
      { slug: "leather-wrapped-spyglass", name: "Leather-Wrapped Handheld Spyglass" },
      { slug: "handheld-brass-spyglass", name: "Retractable Brass Pocket Spyglass" },
      { slug: "handheld-retractable-telescope", name: 'Marine Mini Spyglass 6"' },
    ],
  },
  {
    slug: "brass-telescope-tripod",
    name: "Floor Telescopes on Tripod",
    children: [
      { slug: "vintage-brass-telescope-wood-tripod", name: "Vintage Telescope on Wooden Tripod" },
      { slug: "nautical-spyglass-tripod", name: "Nautical Spyglass on Studio Tripod" },
      { slug: "marine-telescope-brass-tripod", name: "Marine Telescope on Brass Tripod" },
      { slug: "floor-telescope", name: "Adjustable Floor Standing Telescope" },
    ],
  },
  {
    slug: "brass-telescope-stand",
    name: "Tabletop Telescope Stands",
    children: [
      { slug: "tabletop-brass-telescope-stand", name: "Desk Telescope on Short Stand" },
      { slug: "tabletop-telescope-stand", name: "Tabletop Brass Telescope with Base" },
    ],
  },
  {
    slug: "brass-binocular-tripod",
    name: "Observation Binoculars on Tripod",
    children: [
      { slug: "binocular-telescope-wood-tripod", name: "Dual-Head Binocular on Wooden Tripod" },
      { slug: "brass-tripod-binocular", name: "Brass Observation Binocular on Tripod" },
    ],
  },
  {
    slug: "brass-lamp-tripod",
    name: "Marine Tripod Lamps",
    children: [
      { slug: "marine-brass-lamp-tripod", name: "Marine Oil Lamp on Wooden Tripod" },
    ],
  },
  {
    slug: "wooden-ship-wheel",
    name: "Wooden Ship Wheels",
    children: [
      { slug: "handmade-wooden-ship-wheel", name: 'Handmade Teak Ship Wheel 18"' },
    ],
  },
  {
    slug: "royal-lamp-tripod",
    name: "Royal Floor Lamps",
    children: [
      { slug: "royal-brass-lamp-tripod", name: "Royal Brass Floor Lamp on Tripod" },
    ],
  },
  {
    slug: "armor-breast-plate",
    name: "Armor Breast Plate & Jackets",
    children: [
      { slug: "gloves", name: "Steel Armor Combat Gloves" },
    ],
  },
  {
    slug: "armor-helmets",
    name: "Armor Helmets",
    children: [
      { slug: "roman-centurion-helmet", name: "Roman Centurion Helmet with Plume" },
      { slug: "armor-shield", name: "Heraldic Knight Shield" },
      { slug: "norman-knight-helmet", name: "Norman Knight Nasal Helmet" },
      { slug: "movie-replica-armor-helmet", name: "Movie Replica Armor Helmet" },
      { slug: "corinthian-armor-helmet", name: "Corinthian Greek Helmet" },
      { slug: "german-armor-helmet", name: "German Sallet Helmet" },
      { slug: "roman-armor-helmet", name: "Roman Legionary Helmet" },
      { slug: "medieval-armor-helmet", name: "Medieval Great Helm" },
    ],
  },
  {
    slug: "muscle-armour",
    name: "Muscle Armour",
    children: [
      { slug: "steel-shield", name: "Solid Steel Battle Shield" },
      { slug: "armour-shield", name: "Round Brass-Rimmed Shield" },
      { slug: "muscle-armor", name: "Greek Muscle Cuirass" },
      { slug: "leather-muscle-armor", name: "Leather Muscle Cuirass" },
    ],
  },
  {
    slug: "armory-props",
    name: "Armory Props",
    children: [
      { slug: "medieval-shield", name: "Medieval Heater Shield" },
      { slug: "chainmail-armor", name: "Chainmail Hauberk" },
      { slug: "roman-legion-belt", name: "Roman Legion Cingulum Belt" },
      { slug: "armor-shoes-sandals", name: "Roman Armor Caligae Sandals" },
      { slug: "armor-gauntlet", name: "Steel Armor Gauntlet" },
      { slug: "armor-hand-leg-guard", name: "Armor Vambrace & Greave Set" },
      { slug: "armor-shoulder", name: "Armor Pauldron Shoulder Guard" },
    ],
  },
  {
    slug: "compass",
    name: "Compass",
    children: [
      { slug: "push-button-compass", name: "Push-Button Pocket Compass" },
      { slug: "compass-with-lid", name: "Hinged-Lid Desk Compass" },
      { slug: "flat-compass", name: "Flat Card Compass" },
      { slug: "brunton-compass", name: "Brunton Survey Compass" },
      { slug: "sundial-compass", name: "Brass Sundial Compass" },
    ],
  },
  {
    slug: "spotlight-searchlight",
    name: "Spotlight / Searchlight",
    children: [
      { slug: "table-lamp", name: "Brass Cabin Table Lamp" },
      { slug: "spot-light", name: "Marine Deck Spot Light" },
      { slug: "spotlight", name: "Brass Bulkhead Searchlight" },
      { slug: "floor-lamp", name: "Nautical Floor Lantern" },
    ],
  },
  {
    slug: "clocks",
    name: "Clocks",
    children: [
      { slug: "pocket-watches", name: "Brass Open-Face Pocket Watch" },
      { slug: "table-clocks", name: "Maritime Desk Clock" },
      { slug: "brass-table-watch", name: "Brass Table Watch with Compass Dial" },
      { slug: "nautical-pocket-watch", name: "Nautical Pocket Watch on Chain" },
    ],
  },
  {
    slug: "ship-bell",
    name: "Ship Bell",
    children: [
      { slug: "hand-bell", name: "Brass Hand Bell" },
      { slug: "hanging-bell", name: "Hanging Ship Bell with Bracket" },
      { slug: "desk-bell", name: "Captain’s Desk Bell" },
    ],
  },
  {
    slug: "nautical-decor-gifts",
    name: "Nautical Decor & Gifts",
    children: [
      { slug: "brass-burner", name: "Brass Incense Burner" },
      { slug: "pen-holder", name: "Brass Desk Pen Holder" },
      { slug: "wooden-mug", name: "Turned Wooden Tankard" },
      { slug: "wooden-game", name: "Wooden Chess & Board Game" },
      { slug: "wooden-boxes", name: "Wooden Keepsake Boxes" },
      { slug: "wooden-cross", name: "Wooden Cross Pendant" },
      { slug: "game", name: "Nautical Dice & Card Game" },
      { slug: "mirror", name: "Nautical Porthole Mirror" },
      { slug: "home-kitchen", name: "Brass Kitchen Décor Set" },
      { slug: "home-appliances", name: "Nautical Home Accents" },
      { slug: "crystal-wood-crafts", name: "Crystal & Wood Desk Crafts" },
      { slug: "armillary", name: "Brass Armillary Sphere" },
    ],
  },
  {
    slug: "kitchen-product",
    name: "Kitchen Product",
    children: [
      { slug: "wooden-kitchen", name: "Wooden" },
      { slug: "brass-kitchen", name: "Brass" },
      { slug: "cutlery", name: "Cutlery" },
      { slug: "drinkware", name: "Drinkware" },
      { slug: "servewares", name: "Servewares" },
      { slug: "storage-wares", name: "Storage wares" },
      { slug: "tea-strainer-infuser", name: "Tea Strainer / Infuser" },
    ],
  },
  {
    slug: "decor",
    name: "Décor",
    children: [
      { slug: "bikes", name: "Bikes" },
      { slug: "carts", name: "Carts" },
      { slug: "candle-holders", name: "Candle Holders" },
      { slug: "dhokra-art", name: "Dhokra Art" },
      { slug: "key-chain", name: "Key Chains" },
      { slug: "table-decor", name: "Office Decor / Table Decor" },
      { slug: "show-pieces", name: "Showpieces" },
      { slug: "urli", name: "Urli" },
      { slug: "vastu", name: "Vastu" },
      { slug: "wall-frames", name: "Wall Frames" },
    ],
  },
  {
    slug: "jewellery",
    name: "Jewellery",
    children: [
      { slug: "bangles", name: "Bangles" },
      { slug: "bracelet", name: "Bracelet" },
      { slug: "bags-clutch", name: "Bags / Clutch" },
      { slug: "necklace", name: "Necklace" },
      { slug: "jewellery-boxes", name: "Jewellery Boxes" },
    ],
  },
  {
    slug: "hardware",
    name: "Hardware",
    children: [
      { slug: "brackets", name: "Brackets" },
      { slug: "door-handles", name: "Door Handles" },
      { slug: "hangers", name: "Hangers" },
      { slug: "knockers", name: "Knockers" },
      { slug: "locks-keys", name: "Locks & Keys" },
      { slug: "nautical", name: "Nautical" },
    ],
  },
  {
    slug: "modern-brass-wall-sconce",
    name: "Modern Brass Wall Sconce",
    children: [
      { slug: "single-arm-sconce", name: "Single Arm" },
      { slug: "dual-arm-sconce", name: "Dual Arm" },
      { slug: "glass-shade-sconce", name: "Glass Shade" },
      { slug: "outdoor-sconce", name: "Outdoor" },
      { slug: "vintage-sconce", name: "Vintage Finish" },
    ],
  },
];

function product(
  data: Pick<Product, "slug" | "name" | "sku" | "price" | "collection" | "image"> & Partial<Product>
): Product {
  const image = data.image;
  return {
    rating: 4.6,
    reviews: 32,
    stock: "in-stock",
    finish: "Antique / polished",
    material: data.material || "Brass / steel / wood",
    dimensions: data.dimensions || "As pictured",
    weight: "—",
    packaging: "Export carton",
    included: ["Product", "Export packing"],
    description: data.description || data.name,
    story: "Handcrafted for wholesale export from India. Logo and packaging programmes available.",
    moq: 12,
    ...data,
    image,
    gallery: data.gallery || [image],
  };
}

function listing(
  parent: string,
  sub: string,
  name: string,
  sku: string,
  price: number,
  collection: string,
  image: string
): Product {
  return product({
    slug: `${sub}-1`,
    name,
    sku: `${sku}-01`,
    price,
    wholesaleFrom: Number((price * 0.68).toFixed(2)),
    moq: 12,
    collection,
    category: parent,
    subcategory: sub,
    image,
    description: `${name}. Handcrafted for export from our Roorkee factory — logo and packaging programmes available.`,
  });
}

function extra(
  parent: string,
  sub: string,
  n: number,
  name: string,
  sku: string,
  price: number,
  collection: string,
  image: string,
  gallery: string[]
): Product {
  return product({
    slug: `${sub}-${n}`,
    name,
    sku,
    price,
    wholesaleFrom: Number((price * 0.68).toFixed(2)),
    collection,
    category: parent,
    subcategory: sub,
    image,
    gallery,
    description: `${name}. Handcrafted for export from our Roorkee factory — logo and packaging programmes available.`,
  });
}

const armor = [img.armor, img.knight, img.helmet, img.armor];
const helm = [img.helmet, img.knight, img.armor, img.helmet];
const glass = [img.telescope, img.telescopeNight, img.telescopeAstro, img.telescope];
const bins = [img.binoculars, img.binocularsField, img.binocularsMap, img.binoculars];
const comps = [img.compassBrass, img.compassGold, img.compassMap, img.compassBrass];
const lamps = [img.lanternCandle, img.lanternOil, img.lanternVintage, img.lanternCandle];
const time = [img.watch, img.clock, img.watch, img.clock];
const bells = [img.antiques6, img.lanternVintage, img.ship, img.rope];
const wood = [img.workshop, img.gift, img.jewelry, img.globe];
const tripods = [img.tripodWood, img.tripodSpyglass, img.tripodMarine, img.tripodWood];
const binTripods = [img.tripodBinocular, img.binoculars, img.binocularsMap, img.tripodBinocular];
const wheels = [img.shipWheelWood, img.sail, img.sailboat, img.ship];
const lampStands = [img.lampTripod, img.royalLamp, img.lanternVintage, img.lanternOil];

export const shopNowProducts: Product[] = [
  listing("brass-binocular", "handheld-brass-binocular", "Antique Field Binocular 6×30", "MM-BIN-HB", 36, "brass-binoculars", bins[0]),
  listing("brass-binocular", "officer-field-binocular", "Officer Leather Binocular 8×40", "MM-BIN-OF", 42, "brass-binoculars", bins[1]),
  listing("brass-binocular", "brass-handheld-binocular", "Polished Pocket Binocular 4×30", "MM-BIN-HH", 29, "brass-binoculars", bins[2]),
  listing("brass-spyglass-telescope", "leather-wrapped-spyglass", "Leather-Wrapped Handheld Spyglass", "MM-SPY-LW", 48, "telescopes", glass[1]),
  listing("brass-spyglass-telescope", "handheld-brass-spyglass", "Retractable Brass Pocket Spyglass", "MM-SPY-HH", 39, "telescopes", glass[0]),
  listing("brass-spyglass-telescope", "handheld-retractable-telescope", 'Marine Mini Spyglass 6"', "MM-TEL-HR", 4.95, "telescopes", glass[2]),
  listing("brass-telescope-stand", "tabletop-brass-telescope-stand", "Desk Telescope on Short Stand", "MM-STD-TT", 89, "telescopes", tripods[0]),
  listing("brass-telescope-stand", "tabletop-telescope-stand", "Tabletop Brass Telescope with Base", "MM-TEL-TT", 29, "telescopes", glass[0]),
  listing("brass-telescope-tripod", "floor-telescope", "Adjustable Floor Standing Telescope", "MM-TEL-FL", 79, "telescopes", tripods[2]),
  listing("brass-binocular-tripod", "brass-tripod-binocular", "Brass Observation Binocular on Tripod", "MM-BIN-TR", 48, "brass-binoculars", binTripods[0]),
  listing("brass-lamp-tripod", "marine-brass-lamp-tripod", "Marine Oil Lamp on Wooden Tripod", "MM-LMP-TR", 72, "nautical-decor", lampStands[0]),
  listing("wooden-ship-wheel", "handmade-wooden-ship-wheel", 'Handmade Teak Ship Wheel 18"', "MM-WHL-WD", 54, "ship-wheels", wheels[0]),
  listing("royal-lamp-tripod", "royal-brass-lamp-tripod", "Royal Brass Floor Lamp on Tripod", "MM-LMP-RY", 86, "nautical-decor", lampStands[1]),
  listing("armor-breast-plate", "gloves", "Steel Armor Combat Gloves", "MM-GLV", 24, "nautical-decor", armor[0]),
  listing("armor-helmets", "roman-centurion-helmet", "Roman Centurion Helmet with Plume", "MM-HLM-RC", 79, "nautical-decor", helm[0]),
  listing("armor-helmets", "armor-shield", "Heraldic Knight Shield", "MM-HLM-SH", 35, "nautical-decor", armor[1]),
  listing("armor-helmets", "norman-knight-helmet", "Norman Knight Nasal Helmet", "MM-HLM-NK", 88, "nautical-decor", helm[1]),
  listing("armor-helmets", "movie-replica-armor-helmet", "Movie Replica Armor Helmet", "MM-HLM-MV", 95, "nautical-decor", helm[2]),
  listing("armor-helmets", "corinthian-armor-helmet", "Corinthian Greek Helmet", "MM-HLM-CO", 82, "nautical-decor", helm[0]),
  listing("armor-helmets", "german-armor-helmet", "German Sallet Helmet", "MM-HLM-GE", 86, "nautical-decor", helm[1]),
  listing("armor-helmets", "roman-armor-helmet", "Roman Legionary Helmet", "MM-HLM-RA", 79, "nautical-decor", helm[2]),
  listing("armor-helmets", "medieval-armor-helmet", "Medieval Great Helm", "MM-HLM-MD", 84, "nautical-decor", helm[0]),
  listing("muscle-armour", "steel-shield", "Solid Steel Battle Shield", "MM-MSC-SS", 42, "nautical-decor", armor[0]),
  listing("muscle-armour", "armour-shield", "Round Brass-Rimmed Shield", "MM-MSC-AS", 39, "nautical-decor", armor[1]),
  listing("muscle-armour", "muscle-armor", "Greek Muscle Cuirass", "MM-MSC-MA", 249, "nautical-decor", armor[2]),
  listing("muscle-armour", "leather-muscle-armor", "Leather Muscle Cuirass", "MM-MSC-LM", 189, "nautical-decor", armor[3]),
  listing("armory-props", "medieval-shield", "Medieval Heater Shield", "MM-PRP-MS", 32, "nautical-decor", armor[1]),
  listing("armory-props", "chainmail-armor", "Chainmail Hauberk", "MM-PRP-CM", 110, "nautical-decor", armor[0]),
  listing("armory-props", "roman-legion-belt", "Roman Legion Cingulum Belt", "MM-PRP-BL", 28, "nautical-decor", helm[2]),
  listing("armory-props", "armor-shoes-sandals", "Roman Armor Caligae Sandals", "MM-PRP-SH", 36, "nautical-decor", armor[2]),
  listing("armory-props", "armor-gauntlet", "Steel Armor Gauntlet", "MM-PRP-GT", 39, "nautical-decor", helm[0]),
  listing("armory-props", "armor-hand-leg-guard", "Armor Vambrace & Greave Set", "MM-PRP-HG", 44, "nautical-decor", armor[1]),
  listing("armory-props", "armor-shoulder", "Armor Pauldron Shoulder Guard", "MM-PRP-SD", 41, "nautical-decor", armor[0]),
  listing("compass", "push-button-compass", "Push-Button Pocket Compass", "MM-CMP-PB", 5.5, "brass-compasses", comps[0]),
  listing("compass", "compass-with-lid", "Hinged-Lid Desk Compass", "MM-CMP-LD", 6.5, "brass-compasses", comps[1]),
  listing("compass", "flat-compass", "Flat Card Compass", "MM-CMP-FL", 4.8, "brass-compasses", comps[2]),
  listing("compass", "brunton-compass", "Brunton Survey Compass", "MM-CMP-BR", 12, "brass-compasses", comps[3]),
  listing("compass", "sundial-compass", "Brass Sundial Compass", "MM-CMP-SD", 14, "brass-compasses", comps[0]),
  listing("spotlight-searchlight", "table-lamp", "Brass Cabin Table Lamp", "MM-LGT-TL", 22, "nautical-decor", lamps[0]),
  listing("spotlight-searchlight", "spot-light", "Marine Deck Spot Light", "MM-LGT-SP", 28, "nautical-decor", lamps[1]),
  listing("spotlight-searchlight", "spotlight", "Brass Bulkhead Searchlight", "MM-LGT-SL", 32, "nautical-decor", lamps[2]),
  listing("spotlight-searchlight", "floor-lamp", "Nautical Floor Lantern", "MM-LGT-FL", 45, "nautical-decor", lamps[3]),
  listing("clocks", "pocket-watches", "Brass Open-Face Pocket Watch", "MM-CLK-PW", 18, "nautical-instruments", time[0]),
  listing("clocks", "table-clocks", "Maritime Desk Clock", "MM-CLK-TC", 22, "nautical-instruments", time[1]),
  listing("clocks", "brass-table-watch", "Brass Table Watch with Compass Dial", "MM-CLK-TW", 26, "nautical-instruments", time[2]),
  listing("clocks", "nautical-pocket-watch", "Nautical Pocket Watch on Chain", "MM-CLK-NP", 21, "nautical-instruments", time[3]),
  listing("ship-bell", "hand-bell", "Brass Hand Bell", "MM-BEL-HN", 16, "nautical-decor", bells[0]),
  listing("ship-bell", "hanging-bell", "Hanging Ship Bell with Bracket", "MM-BEL-HG", 22, "nautical-decor", bells[1]),
  listing("ship-bell", "desk-bell", "Captain’s Desk Bell", "MM-BEL-DK", 14, "nautical-decor", bells[2]),
  listing("nautical-decor-gifts", "brass-burner", "Brass Incense Burner", "MM-DEC-BR", 18, "corporate-gifts", wood[0]),
  listing("nautical-decor-gifts", "pen-holder", "Brass Desk Pen Holder", "MM-DEC-PH", 8, "corporate-gifts", wood[1]),
  listing("nautical-decor-gifts", "wooden-mug", "Turned Wooden Tankard", "MM-DEC-MG", 7, "corporate-gifts", wood[2]),
  listing("nautical-decor-gifts", "wooden-game", "Wooden Chess & Board Game", "MM-DEC-WG", 15, "corporate-gifts", wood[3]),
  listing("nautical-decor-gifts", "wooden-boxes", "Wooden Keepsake Boxes", "MM-DEC-BX", 12, "corporate-gifts", wood[0]),
  listing("nautical-decor-gifts", "wooden-cross", "Wooden Cross Pendant", "MM-DEC-CR", 2.2, "corporate-gifts", img.jewelry),
  listing("nautical-decor-gifts", "game", "Nautical Dice & Card Game", "MM-DEC-GM", 11, "corporate-gifts", wood[1]),
  listing("nautical-decor-gifts", "mirror", "Nautical Porthole Mirror", "MM-DEC-MR", 28, "nautical-decor", img.lighthouse),
  listing("nautical-decor-gifts", "home-kitchen", "Brass Kitchen Décor Set", "MM-DEC-HK", 16, "corporate-gifts", wood[2]),
  listing("nautical-decor-gifts", "home-appliances", "Nautical Home Accents", "MM-DEC-HA", 19, "corporate-gifts", wood[3]),
  listing("nautical-decor-gifts", "crystal-wood-crafts", "Crystal & Wood Desk Crafts", "MM-DEC-CW", 24, "corporate-gifts", wood[0]),
  listing("nautical-decor-gifts", "armillary", "Brass Armillary Sphere", "MM-DEC-AR", 39, "nautical-instruments", img.globe),
  listing("kitchen-product", "wooden-kitchen", "Hand-Carved Wooden Kitchen Board", "MM-KIT-WD", 14, "corporate-gifts", wood[0]),
  listing("kitchen-product", "brass-kitchen", "Solid Brass Kitchen Serving Set", "MM-KIT-BR", 22, "corporate-gifts", lamps[2]),
  product({
    slug: "cutlery-1",
    name: "Brass Cutlery Set",
    sku: "MM-KIT-CT-01",
    price: 36,
    wholesaleFrom: 24,
    collection: "corporate-gifts",
    category: "kitchen-product",
    subcategory: "cutlery",
    image: img.cutleryGold,
    gallery: [img.cutleryGold, img.cutlerySet, img.cutleryTable],
    description: "Hand-finished brass cutlery for dining and hotel table programmes — fork, knife and spoon in a warm gold tone.",
  }),
  product({
    slug: "drinkware-1",
    name: "Brass Drinkware Tumbler",
    sku: "MM-KIT-DW-01",
    price: 18,
    wholesaleFrom: 12,
    collection: "corporate-gifts",
    category: "kitchen-product",
    subcategory: "drinkware",
    image: img.drinkwareCup,
    gallery: [img.drinkwareCup, img.drinkwareTea, img.drinkwareCoffee],
    description: "Solid brass drinkware for tea, coffee and table service — polished inside, antique or bright outside.",
  }),
  product({
    slug: "servewares-1",
    name: "Brass Serveware Bowl",
    sku: "MM-KIT-SW-01",
    price: 28,
    wholesaleFrom: 18,
    collection: "corporate-gifts",
    category: "kitchen-product",
    subcategory: "servewares",
    image: img.serveBowl,
    gallery: [img.serveBowl, img.servePottery, img.serveTray],
    description: "Brass serveware for platters, bowls and trays — hospitality and wholesale table settings.",
  }),
  product({
    slug: "storage-wares-1",
    name: "Brass Kitchen Storage Canister",
    sku: "MM-KIT-ST-01",
    price: 22,
    wholesaleFrom: 14,
    collection: "corporate-gifts",
    category: "kitchen-product",
    subcategory: "storage-wares",
    image: img.storageJar,
    gallery: [img.storageJar, img.storageCanister, img.storageBox],
    description: "Kitchen storage wares in brass and mixed metal — canisters, jars and boxes for pantry and counter.",
  }),
  product({
    slug: "tea-strainer-infuser-1",
    name: "Brass Tea Strainer / Infuser",
    sku: "MM-KIT-TS-01",
    price: 9.5,
    wholesaleFrom: 6,
    collection: "corporate-gifts",
    category: "kitchen-product",
    subcategory: "tea-strainer-infuser",
    image: img.teaInfuser,
    gallery: [img.teaInfuser, img.teaPot, img.teaStrainer],
    description: "Brass tea strainer and infuser for loose-leaf tea — a small export staple for kitchens and gifting.",
  }),
  listing("decor", "show-pieces", "Brass Showpiece Sculpture", "MM-DCR-SP", 36, "nautical-decor", img.globe),
  listing("decor", "candle-holders", "Antique Brass Candle Holder", "MM-DCR-CH", 18, "nautical-decor", lamps[0]),
  listing("decor", "table-decor", "Office / Table Décor Set", "MM-DCR-TD", 16, "nautical-decor", img.decorOffice),
  listing("decor", "key-chain", "Brass Key Chain", "MM-DCR-KC", 3.5, "corporate-gifts", comps[1]),
  product({
    slug: "bikes-1",
    name: "Decorative Brass Bike",
    sku: "MM-DCR-BK-01",
    price: 34,
    wholesaleFrom: 22,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "bikes",
    image: img.decorBike,
    gallery: [img.decorBike, img.decorCart, img.workshop],
    description: "Handcrafted decorative brass bicycle — a showpiece for desks, shelves and gift programmes.",
  }),
  product({
    slug: "carts-1",
    name: "Decorative Brass Cart",
    sku: "MM-DCR-CT-01",
    price: 29,
    wholesaleFrom: 19,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "carts",
    image: img.decorCart,
    gallery: [img.decorCart, img.decorBike, img.workshop],
    description: "Miniature brass cart for table décor and wholesale gift sets.",
  }),
  product({
    slug: "dhokra-art-1",
    name: "Dhokra Art Brass Figure",
    sku: "MM-DCR-DK-01",
    price: 38,
    wholesaleFrom: 25,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "dhokra-art",
    image: img.decorDhokra,
    gallery: [img.decorDhokra, img.workshop, img.globe],
    description: "Traditional Dhokra-style brass art — lost-wax metal craft for collectors and décor buyers.",
  }),
  product({
    slug: "urli-1",
    name: "Brass Urli Bowl",
    sku: "MM-DCR-UR-01",
    price: 26,
    wholesaleFrom: 17,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "urli",
    image: img.decorUrli,
    gallery: [img.decorUrli, img.serveBowl, img.serveTray],
    description: "Classic brass urli for flowers, floating candles and festive table décor.",
  }),
  product({
    slug: "vastu-1",
    name: "Vastu Brass Accent",
    sku: "MM-DCR-VS-01",
    price: 21,
    wholesaleFrom: 14,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "vastu",
    image: img.decorVastu,
    gallery: [img.decorVastu, img.lanternCandle, img.globe],
    description: "Vastu brass décor for home and office — compact pieces for wholesale and gifting.",
  }),
  product({
    slug: "wall-frames-1",
    name: "Brass Wall Frame",
    sku: "MM-DCR-WF-01",
    price: 24,
    wholesaleFrom: 16,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "wall-frames",
    image: img.decorFrame,
    gallery: [img.decorFrame, img.lighthouse, img.workshop],
    description: "Brass wall frames for emblems, motifs and decorative hangings.",
  }),
  product({
    slug: "ashok-stambh-1",
    name: "Ashok Stambh Table Décor",
    sku: "MM-DCR-AS-01",
    price: 22,
    wholesaleFrom: 14,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.decorAshok,
    gallery: [img.decorAshok, img.decorOffice, img.globe],
    description: "Brass Ashok Stambh for office desks and table décor.",
  }),
  product({
    slug: "office-compass-1",
    name: "Brass Desk Compass",
    sku: "MM-DCR-CP-01",
    price: 18,
    wholesaleFrom: 12,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.compassBrass,
    gallery: [img.compassBrass, img.compassGold, img.decorOffice],
    description: "Table compass for office décor and executive gifting.",
  }),
  product({
    slug: "office-flag-1",
    name: "Desk Flag Stand",
    sku: "MM-DCR-FG-01",
    price: 14,
    wholesaleFrom: 9,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.decorFlag,
    gallery: [img.decorFlag, img.decorOffice, img.workshop],
    description: "Brass desk flag stand for office and table décor.",
  }),
  product({
    slug: "flower-vase-1",
    name: "Brass Flower Vase",
    sku: "MM-DCR-FV-01",
    price: 19,
    wholesaleFrom: 12,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.decorVase,
    gallery: [img.decorVase, img.decorUrli, img.serveBowl],
    description: "Brass flower vase for table and office décor.",
  }),
  product({
    slug: "ink-pot-1",
    name: "Brass Ink Pot",
    sku: "MM-DCR-IP-01",
    price: 11,
    wholesaleFrom: 7,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.antiques5,
    gallery: [img.antiques5, img.decorOffice, img.workshop],
    description: "Desk ink pot in brass — a classic office table accent.",
  }),
  product({
    slug: "kalpvriksha-1",
    name: "Kalpvriksha Table Décor",
    sku: "MM-DCR-KV-01",
    price: 27,
    wholesaleFrom: 18,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.workshop,
    gallery: [img.workshop, img.decorAshok, img.globe],
    description: "Kalpvriksha brass tree for office and table décor.",
  }),
  product({
    slug: "paper-weight-1",
    name: "Brass Paper Weight",
    sku: "MM-DCR-PW-01",
    price: 8,
    wholesaleFrom: 5,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.antiques3,
    gallery: [img.antiques3, img.decorOffice, img.workshop],
    description: "Solid brass paper weight for desks and office décor.",
  }),
  product({
    slug: "sand-clock-1",
    name: "Brass Sand Clock",
    sku: "MM-DCR-SC-01",
    price: 16,
    wholesaleFrom: 10,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.hourglass,
    gallery: [img.hourglass, img.hourglassSand, img.clock],
    description: "Sand clock / hourglass for table décor.",
  }),
  product({
    slug: "table-clock-1",
    name: "Brass Table Clock",
    sku: "MM-DCR-TC-01",
    price: 21,
    wholesaleFrom: 14,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "table-decor",
    image: img.clock,
    gallery: [img.clock, img.watch, img.hourglass],
    description: "Brass table clock for office desks and décor sets.",
  }),
  product({
    slug: "taj-mahal-1",
    name: "Taj Mahal Showpiece",
    sku: "MM-DCR-TJ-01",
    price: 44,
    wholesaleFrom: 29,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "show-pieces",
    image: img.decorTaj,
    gallery: [img.decorTaj, img.decorAshok, img.globe],
    description: "Brass Taj Mahal showpiece for home and gift programmes.",
  }),
  product({
    slug: "ashok-emblem-1",
    name: "Ashok Emblem Wall Frame",
    sku: "MM-DCR-AE-01",
    price: 23,
    wholesaleFrom: 15,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "wall-frames",
    image: img.decorAshok,
    gallery: [img.decorAshok, img.decorFrame, img.workshop],
    description: "Ashok Emblem in a brass wall frame.",
  }),
  product({
    slug: "animal-frame-1",
    name: "Animals Wall Frame",
    sku: "MM-DCR-AN-01",
    price: 20,
    wholesaleFrom: 13,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "wall-frames",
    image: img.decorAnimal,
    gallery: [img.decorAnimal, img.decorFrame, img.workshop],
    description: "Animal motif brass wall frame.",
  }),
  product({
    slug: "kalpvriksha-frame-1",
    name: "Kalpvriksha Wall Frame",
    sku: "MM-DCR-KF-01",
    price: 22,
    wholesaleFrom: 14,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "wall-frames",
    image: img.workshop,
    gallery: [img.workshop, img.decorFrame, img.decorAshok],
    description: "Kalpvriksha motif in a brass wall frame.",
  }),
  product({
    slug: "lotus-frame-1",
    name: "Lotus Wall Frame",
    sku: "MM-DCR-LT-01",
    price: 19,
    wholesaleFrom: 12,
    collection: "nautical-decor",
    category: "decor",
    subcategory: "wall-frames",
    image: img.decorLotus,
    gallery: [img.decorLotus, img.decorFrame, img.decorUrli],
    description: "Lotus motif brass wall frame.",
  }),
  product({
    slug: "bangles-1",
    name: "Handcrafted Brass Bangles",
    sku: "MM-JWL-BG-01",
    price: 8,
    wholesaleFrom: 5.5,
    collection: "corporate-gifts",
    category: "jewellery",
    subcategory: "bangles",
    image: img.jewelryBangle,
    gallery: [img.jewelryBangle, img.jewelryBracelet, img.jewelryNecklace],
    description: "Handcrafted brass bangles — polished and antique finishes for retail and wholesale.",
  }),
  product({
    slug: "bracelet-1",
    name: "Antique Brass Bracelet",
    sku: "MM-JWL-BR-01",
    price: 9.5,
    wholesaleFrom: 6.5,
    collection: "corporate-gifts",
    category: "jewellery",
    subcategory: "bracelet",
    image: img.jewelryBracelet,
    gallery: [img.jewelryBracelet, img.jewelryBangle, img.jewelryNecklace],
    description: "Antique-finish brass bracelet for jewellery programmes and gifting.",
  }),
  product({
    slug: "bags-clutch-1",
    name: "Brass-Clasp Evening Clutch",
    sku: "MM-JWL-CL-01",
    price: 28,
    wholesaleFrom: 18,
    collection: "corporate-gifts",
    category: "jewellery",
    subcategory: "bags-clutch",
    image: img.jewelryBag,
    gallery: [img.jewelryBag, img.gift, img.jewelryBox],
    description: "Evening bag / clutch with brass clasp — a jewellery-adjacent gift piece.",
  }),
  product({
    slug: "necklace-1",
    name: "Statement Brass Necklace",
    sku: "MM-JWL-NK-01",
    price: 12,
    wholesaleFrom: 8,
    collection: "corporate-gifts",
    category: "jewellery",
    subcategory: "necklace",
    image: img.jewelryNecklace,
    gallery: [img.jewelryNecklace, img.jewelryBangle, img.jewelryBracelet],
    description: "Statement brass necklace for retail counters and export jewellery lots.",
  }),
  product({
    slug: "jewellery-boxes-1",
    name: "Jewellery Box",
    sku: "MM-JWL-BX-01",
    price: 19,
    wholesaleFrom: 12,
    collection: "corporate-gifts",
    category: "jewellery",
    subcategory: "jewellery-boxes",
    image: img.jewelryBox,
    gallery: [img.jewelryBox, img.gift, img.workshop],
    description: "Jewellery box with brass inlay — for sets, gifting and wholesale packing.",
  }),
  listing("hardware", "brackets", "Solid Brass Wall Bracket", "MM-HDW-BK", 11, "nautical-decor", wood[2]),
  listing("hardware", "door-handles", "Antique Brass Door Handle", "MM-HDW-DH", 15, "nautical-decor", wood[0]),
  listing("hardware", "hangers", "Brass Coat Hanger Hook", "MM-HDW-HG", 7.5, "nautical-decor", wood[3]),
  listing("hardware", "knockers", "Lion Head Door Knocker", "MM-HDW-KN", 21, "nautical-decor", img.antiques5),
  listing("hardware", "locks-keys", "Brass Lock & Skeleton Key Set", "MM-HDW-LK", 13, "nautical-decor", img.antiques3),
  product({
    slug: "nautical-1",
    name: "Nautical Brass Hardware",
    sku: "MM-HDW-NT-01",
    price: 18,
    wholesaleFrom: 12,
    collection: "nautical-decor",
    category: "hardware",
    subcategory: "nautical",
    image: img.hwNautical,
    gallery: [img.hwNautical, img.rope, img.ship, img.sailboat],
    description: "Nautical brass hardware — marine fittings, deck pieces and ship-style hardware for export.",
  }),
  product({
    slug: "single-arm-sconce-1",
    name: "Single-Arm Brass Wall Sconce",
    sku: "MM-WSC-SA-01",
    price: 42,
    wholesaleFrom: 28,
    collection: "modern-brass-wall-sconce",
    category: "modern-brass-wall-sconce",
    subcategory: "single-arm-sconce",
    image: img.sconceWall,
    gallery: [img.sconceWall, img.sconceModern, img.sconceBrass, img.sconceVintage],
    description: "Single-arm modern brass wall sconce with a warm shade — for hallways, hotels and dining rooms.",
  }),
  product({
    slug: "dual-arm-sconce-1",
    name: "Dual-Arm Brass Wall Sconce",
    sku: "MM-WSC-DA-01",
    price: 58,
    wholesaleFrom: 39,
    collection: "modern-brass-wall-sconce",
    category: "modern-brass-wall-sconce",
    subcategory: "dual-arm-sconce",
    image: img.sconceBrass,
    gallery: [img.sconceBrass, img.sconcePendant, img.sconceWall, img.sconceInterior],
    description: "Dual-arm brass wall sconce — balanced arms and a polished finish for lobbies and stairwells.",
  }),
  product({
    slug: "glass-shade-sconce-1",
    name: "Glass-Shade Brass Wall Sconce",
    sku: "MM-WSC-GS-01",
    price: 46,
    wholesaleFrom: 31,
    collection: "modern-brass-wall-sconce",
    category: "modern-brass-wall-sconce",
    subcategory: "glass-shade-sconce",
    image: img.sconceModern,
    gallery: [img.sconceModern, img.sconceWall, img.sconceVintage, img.sconcePendant],
    description: "Brass wall sconce with a frosted glass shade — soft light for bedrooms and hotel corridors.",
  }),
  product({
    slug: "outdoor-sconce-1",
    name: "Outdoor Brass Wall Sconce",
    sku: "MM-WSC-OD-01",
    price: 52,
    wholesaleFrom: 35,
    collection: "modern-brass-wall-sconce",
    category: "modern-brass-wall-sconce",
    subcategory: "outdoor-sconce",
    image: img.sconceInterior,
    gallery: [img.sconceInterior, img.sconceWall, img.sconceBrass, img.sconceVintage],
    description: "Weather-ready brass wall sconce for porches, courtyards and covered outdoor walls.",
  }),
  product({
    slug: "vintage-sconce-1",
    name: "Vintage-Finish Brass Wall Sconce",
    sku: "MM-WSC-VF-01",
    price: 44,
    wholesaleFrom: 30,
    collection: "modern-brass-wall-sconce",
    category: "modern-brass-wall-sconce",
    subcategory: "vintage-sconce",
    image: img.sconceVintage,
    gallery: [img.sconceVintage, img.sconceWall, img.sconceModern, img.sconceInterior],
    description: "Antique-finish brass wall sconce — aged metal and warm light for period interiors.",
  }),
  product({
    slug: "vintage-brass-telescope-wooden-tripod",
    name: "Vintage Telescope on Wooden Tripod",
    sku: "MM-TEL-TR-01",
    price: 189,
    wholesaleFrom: 129,
    moq: 4,
    rating: 4.8,
    reviews: 64,
    collection: "telescopes",
    category: "brass-telescope-tripod",
    subcategory: "vintage-brass-telescope-wood-tripod",
    finish: "Antique brass, leather wrap",
    material: "Solid brass, genuine leather, hardwood tripod",
    dimensions: 'Floor standing · 36"–60" adjustable',
    featured: true,
    image: img.tripodWood,
    gallery: [img.tripodWood, img.tripodSpyglass, img.telescope],
    description:
      "A floor-standing vintage brass telescope with leather wrap and a hardwood tripod. Built for actual viewing and for nautical interiors, hotels and wholesale display.",
  }),
  product({
    slug: "vintage-brass-nautical-spyglass-tripod",
    name: "Nautical Spyglass on Studio Tripod",
    sku: "MM-TEL-TR-02",
    price: 198,
    wholesaleFrom: 138,
    moq: 4,
    rating: 4.7,
    reviews: 41,
    collection: "telescopes",
    category: "brass-telescope-tripod",
    subcategory: "nautical-spyglass-tripod",
    finish: "Polished nickel / antique brass",
    material: "Brass barrel, optical glass, hardwood tripod",
    dimensions: 'Floor standing · 40"–62" adjustable',
    featured: true,
    image: img.tripodSpyglass,
    gallery: [img.tripodSpyglass, img.tripodWood, img.telescopeNight],
    description:
      "Nautical spyglass on a studio tripod — a presentation piece for showrooms and a working instrument for collectors.",
  }),
  product({
    slug: "handcrafted-brass-binocular-telescope-tripod",
    name: "Dual-Head Binocular on Wooden Tripod",
    sku: "MM-BIN-TR-01",
    price: 245,
    wholesaleFrom: 168,
    moq: 2,
    rating: 4.9,
    reviews: 38,
    collection: "brass-binoculars",
    category: "brass-binocular-tripod",
    subcategory: "binocular-telescope-wood-tripod",
    finish: "Polished brass",
    material: "Solid brass binocular head, hardwood tripod",
    dimensions: 'Floor standing · dual 20×80 style head',
    featured: true,
    image: img.tripodBinocular,
    gallery: [img.tripodBinocular, img.binoculars, img.binocularsMap],
    description:
      "Handcrafted brass binocular telescope on a wooden tripod — dual optics for viewing and a statement piece for lobbies and trade floors.",
  }),
  product({
    slug: "vintage-style-brass-marine-telescope-tripod",
    name: "Marine Telescope on Brass Tripod",
    sku: "MM-TEL-TR-03",
    price: 219,
    wholesaleFrom: 158,
    moq: 4,
    rating: 4.8,
    reviews: 52,
    collection: "telescopes",
    category: "brass-telescope-tripod",
    subcategory: "marine-telescope-brass-tripod",
    finish: "Full polished brass",
    material: "Solid brass barrel and tripod, optical glass",
    dimensions: 'Floor standing · 42"–64" adjustable',
    featured: true,
    image: img.tripodMarine,
    gallery: [img.tripodMarine, img.tripodWood, img.telescope],
    description:
      "Full-brass marine telescope on a matching brass tripod. Export-ready for retailers, hotels and nautical collections.",
  }),
  extra("kitchen-product", "wooden-kitchen", 2, "Wooden Serving Spoon Set", "MM-KIT-WD-02", 11, "corporate-gifts", img.serveTray, [img.serveTray, img.storageBox, img.cutleryTable]),
  extra("kitchen-product", "wooden-kitchen", 3, "Carved Wooden Spice Box", "MM-KIT-WD-03", 16, "corporate-gifts", img.storageBox, [img.storageBox, img.servePottery, img.workshop]),
  extra("kitchen-product", "brass-kitchen", 2, "Brass Kitchen Ladle Set", "MM-KIT-BR-02", 19, "corporate-gifts", img.cutleryGold, [img.cutleryGold, img.serveBowl, lamps[2]]),
  extra("kitchen-product", "brass-kitchen", 3, "Brass Cookware Kadhai", "MM-KIT-BR-03", 32, "corporate-gifts", img.servePottery, [img.servePottery, img.serveBowl, img.cutlerySet]),
  extra("kitchen-product", "cutlery", 2, "Antique Brass Spoon Set", "MM-KIT-CT-02", 24, "corporate-gifts", img.cutlerySet, [img.cutlerySet, img.cutleryGold, img.cutleryTable]),
  extra("kitchen-product", "cutlery", 3, "Hotel Brass Fork & Knife", "MM-KIT-CT-03", 29, "corporate-gifts", img.cutleryTable, [img.cutleryTable, img.cutlerySet, img.cutleryGold]),
  extra("kitchen-product", "drinkware", 2, "Brass Coffee Mug", "MM-KIT-DW-02", 14, "corporate-gifts", img.drinkwareCoffee, [img.drinkwareCoffee, img.drinkwareCup, img.drinkwareTea]),
  extra("kitchen-product", "drinkware", 3, "Brass Tea Cup Pair", "MM-KIT-DW-03", 21, "corporate-gifts", img.drinkwareTea, [img.drinkwareTea, img.teaPot, img.drinkwareCup]),
  extra("kitchen-product", "servewares", 2, "Brass Serving Tray", "MM-KIT-SW-02", 26, "corporate-gifts", img.serveTray, [img.serveTray, img.serveBowl, img.servePottery]),
  extra("kitchen-product", "servewares", 3, "Brass Serving Platter", "MM-KIT-SW-03", 31, "corporate-gifts", img.servePottery, [img.servePottery, img.serveTray, img.serveBowl]),
  extra("kitchen-product", "storage-wares", 2, "Brass Spice Jar Pair", "MM-KIT-ST-02", 17, "corporate-gifts", img.storageCanister, [img.storageCanister, img.storageJar, img.storageBox]),
  extra("kitchen-product", "storage-wares", 3, "Kitchen Storage Box", "MM-KIT-ST-03", 20, "corporate-gifts", img.storageBox, [img.storageBox, img.storageJar, img.storageCanister]),
  extra("kitchen-product", "tea-strainer-infuser", 2, "Loose-Leaf Tea Strainer", "MM-KIT-TS-02", 8, "corporate-gifts", img.teaStrainer, [img.teaStrainer, img.teaInfuser, img.teaPot]),
  extra("kitchen-product", "tea-strainer-infuser", 3, "Brass Tea Infuser Ball", "MM-KIT-TS-03", 7.5, "corporate-gifts", img.teaPot, [img.teaPot, img.teaInfuser, img.drinkwareTea]),
  extra("decor", "bikes", 2, "Polished Brass Cycle Model", "MM-DCR-BK-02", 38, "nautical-decor", img.workshop, [img.workshop, img.decorBike, img.decorCart]),
  extra("decor", "bikes", 3, "Vintage Brass Tricycle Décor", "MM-DCR-BK-03", 41, "nautical-decor", img.decorCart, [img.decorCart, img.decorBike, img.globe]),
  extra("decor", "carts", 2, "Brass Hand Cart Model", "MM-DCR-CT-02", 27, "nautical-decor", img.workshop, [img.workshop, img.decorCart, img.decorBike]),
  extra("decor", "carts", 3, "Miniature Wagon Cart", "MM-DCR-CT-03", 31, "nautical-decor", img.globe, [img.globe, img.decorCart, img.workshop]),
  extra("decor", "candle-holders", 2, "Brass Pillar Candle Stand", "MM-DCR-CH-02", 16, "nautical-decor", lamps[1], [lamps[1], lamps[2], img.lanternCandle]),
  extra("decor", "candle-holders", 3, "Twin-Arm Candle Holder", "MM-DCR-CH-03", 22, "nautical-decor", lamps[2], [lamps[2], lamps[0], img.lanternVintage]),
  extra("decor", "dhokra-art", 2, "Dhokra Tribal Horse", "MM-DCR-DK-02", 42, "nautical-decor", img.decorAnimal, [img.decorAnimal, img.decorDhokra, img.workshop]),
  extra("decor", "dhokra-art", 3, "Dhokra Tree of Life", "MM-DCR-DK-03", 45, "nautical-decor", img.workshop, [img.workshop, img.decorDhokra, img.globe]),
  extra("decor", "key-chain", 2, "Antique Brass Key Fob", "MM-DCR-KC-02", 4, "corporate-gifts", comps[0], [comps[0], comps[2], img.watch]),
  extra("decor", "key-chain", 3, "Ship-Wheel Key Chain", "MM-DCR-KC-03", 4.5, "corporate-gifts", img.shipWheelWood, [img.shipWheelWood, comps[1], img.rope]),
  extra("decor", "show-pieces", 2, "Brass Animal Showpiece", "MM-DCR-SP-02", 33, "nautical-decor", img.decorAnimal, [img.decorAnimal, img.globe, img.decorTaj]),
  extra("decor", "urli", 2, "Large Festive Urli", "MM-DCR-UR-02", 34, "nautical-decor", img.serveBowl, [img.serveBowl, img.decorUrli, img.serveTray]),
  extra("decor", "urli", 3, "Mini Table Urli", "MM-DCR-UR-03", 18, "nautical-decor", img.servePottery, [img.servePottery, img.decorUrli, img.serveBowl]),
  extra("decor", "vastu", 2, "Brass Tortoise Vastu", "MM-DCR-VS-02", 15, "nautical-decor", lamps[0], [lamps[0], img.decorVastu, img.globe]),
  extra("decor", "vastu", 3, "Vastu Pyramid Accent", "MM-DCR-VS-03", 19, "nautical-decor", img.globe, [img.globe, img.decorVastu, img.decorAshok]),
  extra("jewellery", "bangles", 2, "Antique Pair of Bangles", "MM-JWL-BG-02", 10, "corporate-gifts", img.jewelryBracelet, [img.jewelryBracelet, img.jewelryBangle, img.jewelryGold]),
  extra("jewellery", "bangles", 3, "Polished Brass Bangle Set", "MM-JWL-BG-03", 12, "corporate-gifts", img.jewelryGold, [img.jewelryGold, img.jewelryBangle, img.jewelryNecklace]),
  extra("jewellery", "bracelet", 2, "Link Brass Bracelet", "MM-JWL-BR-02", 11, "corporate-gifts", img.jewelryGold, [img.jewelryGold, img.jewelryBracelet, img.jewelryBangle]),
  extra("jewellery", "bracelet", 3, "Brass Cuff Bracelet", "MM-JWL-BR-03", 13, "corporate-gifts", img.jewelryBangle, [img.jewelryBangle, img.jewelryBracelet, img.jewelry]),
  extra("jewellery", "bags-clutch", 2, "Embroidered Evening Clutch", "MM-JWL-CL-02", 32, "corporate-gifts", img.gift, [img.gift, img.jewelryBag, img.jewelryBox]),
  extra("jewellery", "bags-clutch", 3, "Brass-Frame Potli Bag", "MM-JWL-CL-03", 24, "corporate-gifts", img.jewelryBox, [img.jewelryBox, img.jewelryBag, img.gift]),
  extra("jewellery", "necklace", 2, "Brass Pendant Necklace", "MM-JWL-NK-02", 14, "corporate-gifts", img.jewelryGold, [img.jewelryGold, img.jewelryNecklace, img.jewelry]),
  extra("jewellery", "necklace", 3, "Layered Brass Necklace", "MM-JWL-NK-03", 16, "corporate-gifts", img.jewelry, [img.jewelry, img.jewelryNecklace, img.jewelryBangle]),
  extra("jewellery", "jewellery-boxes", 2, "Travel Jewellery Case", "MM-JWL-BX-02", 22, "corporate-gifts", img.gift, [img.gift, img.jewelryBox, img.workshop]),
  extra("jewellery", "jewellery-boxes", 3, "Inlaid Ring Box", "MM-JWL-BX-03", 11, "corporate-gifts", img.workshop, [img.workshop, img.jewelryBox, img.gift]),
  extra("hardware", "brackets", 2, "Corner Shelf Bracket", "MM-HDW-BK-02", 9, "nautical-decor", wood[0], [wood[0], wood[2], img.workshop]),
  extra("hardware", "brackets", 3, "Heavy-Duty L Bracket", "MM-HDW-BK-03", 13, "nautical-decor", img.workshop, [img.workshop, wood[2], img.antiques3]),
  extra("hardware", "door-handles", 2, "Mortice Door Handle Pair", "MM-HDW-DH-02", 18, "nautical-decor", wood[1], [wood[1], wood[0], img.antiques]),
  extra("hardware", "door-handles", 3, "Brass Pull Handle Bar", "MM-HDW-DH-03", 16, "nautical-decor", img.antiques, [img.antiques, wood[0], img.workshop]),
  extra("hardware", "hangers", 2, "Wall Coat Hook Pair", "MM-HDW-HG-02", 8, "nautical-decor", img.rope, [img.rope, wood[3], img.workshop]),
  extra("hardware", "hangers", 3, "Brass Robe Hanger", "MM-HDW-HG-03", 9, "nautical-decor", wood[2], [wood[2], img.rope, wood[3]]),
  extra("hardware", "knockers", 2, "Ring Door Knocker", "MM-HDW-KN-02", 19, "nautical-decor", img.antiques4, [img.antiques4, img.antiques5, img.ship]),
  extra("hardware", "knockers", 3, "Anchor Door Knocker", "MM-HDW-KN-03", 23, "nautical-decor", img.ship, [img.ship, img.antiques5, img.rope]),
  extra("hardware", "locks-keys", 2, "Brass Padlock with Key", "MM-HDW-LK-02", 11, "nautical-decor", img.antiques5, [img.antiques5, img.antiques3, img.clock]),
  extra("hardware", "locks-keys", 3, "Antique Rim Lock Set", "MM-HDW-LK-03", 17, "nautical-decor", img.clock, [img.clock, img.antiques3, img.workshop]),
  extra("hardware", "nautical", 2, "Marine Brass Cleat", "MM-HDW-NT-02", 14, "nautical-decor", img.rope, [img.rope, img.hwNautical, img.ship]),
  extra("hardware", "nautical", 3, "Porthole Hardware Ring", "MM-HDW-NT-03", 21, "nautical-decor", img.lighthouse, [img.lighthouse, img.hwNautical, img.sailboat]),
  extra("modern-brass-wall-sconce", "single-arm-sconce", 2, "Slim Single-Arm Sconce", "MM-WSC-SA-02", 39, "modern-brass-wall-sconce", img.sconceModern, [img.sconceModern, img.sconceWall, img.sconceBrass]),
  extra("modern-brass-wall-sconce", "single-arm-sconce", 3, "Hotel Single-Arm Sconce", "MM-WSC-SA-03", 48, "modern-brass-wall-sconce", img.sconceInterior, [img.sconceInterior, img.sconceWall, img.sconceVintage]),
  extra("modern-brass-wall-sconce", "dual-arm-sconce", 2, "Grand Dual-Arm Sconce", "MM-WSC-DA-02", 64, "modern-brass-wall-sconce", img.sconcePendant, [img.sconcePendant, img.sconceBrass, img.sconceWall]),
  extra("modern-brass-wall-sconce", "dual-arm-sconce", 3, "Stair Dual-Arm Sconce", "MM-WSC-DA-03", 55, "modern-brass-wall-sconce", img.sconceWall, [img.sconceWall, img.sconceBrass, img.sconceInterior]),
  extra("modern-brass-wall-sconce", "glass-shade-sconce", 2, "Opal Glass Wall Sconce", "MM-WSC-GS-02", 49, "modern-brass-wall-sconce", img.sconcePendant, [img.sconcePendant, img.sconceModern, img.sconceVintage]),
  extra("modern-brass-wall-sconce", "glass-shade-sconce", 3, "Clear Glass Dome Sconce", "MM-WSC-GS-03", 47, "modern-brass-wall-sconce", img.sconceInterior, [img.sconceInterior, img.sconceModern, img.sconcePendant]),
  extra("modern-brass-wall-sconce", "outdoor-sconce", 2, "Porch Outdoor Sconce", "MM-WSC-OD-02", 54, "modern-brass-wall-sconce", img.sconceVintage, [img.sconceVintage, img.sconceInterior, img.lanternVintage]),
  extra("modern-brass-wall-sconce", "outdoor-sconce", 3, "Lantern Outdoor Sconce", "MM-WSC-OD-03", 56, "modern-brass-wall-sconce", img.lanternVintage, [img.lanternVintage, img.sconceInterior, img.sconceWall]),
  extra("modern-brass-wall-sconce", "vintage-sconce", 2, "Aged Brass Wall Sconce", "MM-WSC-VF-02", 41, "modern-brass-wall-sconce", img.sconceBrass, [img.sconceBrass, img.sconceVintage, img.sconceWall]),
  extra("modern-brass-wall-sconce", "vintage-sconce", 3, "Dark Patina Wall Sconce", "MM-WSC-VF-03", 46, "modern-brass-wall-sconce", img.sconceWall, [img.sconceWall, img.sconceVintage, img.sconceInterior]),
];

export function findShopNowLabel(slug: string | null) {
  if (!slug) return "Shop Now";
  for (const parent of shopNowTree) {
    if (parent.slug === slug) return parent.name;
    const child = parent.children.find((c) => c.slug === slug);
    if (child) return child.name;
  }
  return "Shop Now";
}
